### ISSUE TITLE
Consider to add a mention to shx as a solution for cross-platform npm scripts

### ISSUE THREAD

**Issue by janluke** [fullstack-hy2020/fullstack-hy2020.github.io#1021]
In [Part 3](https://fullstackopen.com/en/part3/deploying_app_to_internet#streamlining-deploying-of-the-frontend), you advise Windows users to configure npm to use git bash as default npm shell:
```
npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
```
This is an okay solution for the course but for real projects there are alternatives that don't require any manual step besides of `npm install` to have a functioning package, for example [shx](https://www.npmjs.com/package/shx).

Maybe, you can mention this.

**Comment by mluukkai** [comment]
done in 2022 edition!
