### ISSUE TITLE
Part 11: Missing exercise 11.13

### ISSUE THREAD

**Issue by anttipessa** [fullstack-hy2020/fullstack-hy2020.github.io#1029]
Deployment part ends with exercise 12 and the next part starts with exercise 14.

**Comment by spezzers** [comment]
I haven't started part 11 yet but was just browsing and noticed this. Is there an exercise missing or is it just a numbering typo?

**Comment by mluukkai** [comment]
I made a mistake in calculations. Have not yet decided how to solve this!

**Comment by mluukkai** [comment]
fixd
