### ISSUE TITLE
Spanish translations for part names

### ISSUE THREAD

**Issue by Kaltsoon** [fullstack-hy2020/fullstack-hy2020.github.io#1049]
We need help translating the part names in Spanish: https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/source/src/content/partnavigation/partnavigation.js#L211.

Perhaps @sebastiantorres86 or someone else could help us with this?

**Comment by EntwistleOx** [comment]
Hi!! i would like to collaborate with the spanish translation maybe in current or future issues :)
