### ISSUE TITLE
Steps missing in 9d section Create React App with TypeScript?

### ISSUE THREAD

**Issue by nikomn** [fullstack-hy2020/fullstack-hy2020.github.io#1067]
There seems to maybe be some steps missing as following the steps in the material do not seem to cause any "no-use-before-define" eslint errors? There does not seem to be a file serviceWorker.ts in the src-folder and also no "register function" seems to exist in any file?

The contents of src-folder created with command 

`npx create-react-app my-app --template typescript` 

are:

- App.css
- App.test.tsx
- App.tsx
- index.css
- index.tsx
- logo.svg
- react-app-env.d.ts
- reportWebVitals.ts
- setupTests.ts

Running the command

`npm run lint` 

does not report any "no-use-before-define" errors, only two "warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types" errors.

(Tested this on node v12.18.2 & v10.23.0 with npm & npx v. 6.14.5)

**Comment by module17** [comment]
Also getting the same errors here.  I think it could have something to do with a recent update to `create-react-app`.

```
npm run lint

> courseinfo-ts@0.1.0 lint
> eslint './src/**/*.{ts,tsx}'


.../courseinfo-ts/src/App.tsx
  5:1  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

.../courseinfo-ts/src/reportWebVitals.ts
  3:25  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

✖ 2 problems (0 errors, 2 warnings)
```

**Comment by mluukkai** [comment]
should be ok now
