### ISSUE TITLE
Exercise 9.6 Typescript problem

### ISSUE THREAD

**Issue by lansinq** [fullstack-hy2020/fullstack-hy2020.github.io#1073]
```
// calculator.ts

type Operation = 'add' | 'multiply' | 'divide';
type Result = number;
export const calculator = (a: number, b: number, op : Operation) : Result => { ... }
```

```
// index.ts

app.get('/calculate', (req, res) => {
  const { value1, value2, op } = req.query;
  const result = calculator(value1, value2, op);
  res.send(result);
});
```

`value1` is highlighted as error with message:
```
const value1: string | QueryString.ParsedQs | string[] | QueryString.ParsedQs[] | undefined
Argument of type 'string | ParsedQs | string[] | ParsedQs[] | undefined' is not assignable to parameter of type 'number'.
Type 'undefined' is not assignable to type 'number'.ts(2345)
```

Both `value1, value2` errors can be solved by casting them to `Number` when passing them to `calculator` even though no such thing is done in example code which appears to pass with no errors. After fixing those two problems `op` gets a similar error message:
```
const op: string | QueryString.ParsedQs | string[] | QueryString.ParsedQs[] | undefined
Argument of type 'string | ParsedQs | string[] | ParsedQs[] | undefined' is not assignable to parameter of type 'Operation'.
Type 'undefined' is not assignable to type 'Operation'.ts(2345)
```
Pretty sure the problem is that `Operation` type expects values to be any of `'add' | 'multiply' | 'divide'` and an unknown string doesn't satisfy it.

How do I fix this problem?

**Comment by Kaltsoon** [comment]
This should work:

```javascript
const { query } = req;
const value1 = parseInt(query.value1) as number;
const value2 = parseInt(query.value2) as number;
const op = query.op as Operation;

// ...
```

However validating the query and not just expecting the types would be a good idea.

**Comment by lansinq** [comment]
That works.

> However validating the query and not just expecting the types would be a good idea.

This wasn't part of an exercise but a sample code leading up to it that instructor wrote. There are quite a few occasions where  this happens in part 9 where instructor code seems to be fine but then when I try to rewrite it using the same configuration I get tons of underlined lines marked as errors that require fixing.
