### ISSUE TITLE
4b supertest: mismatch between console warning and proposed solution for it

### ISSUE THREAD

**Issue by mmm-ui** [fullstack-hy2020/fullstack-hy2020.github.io#1086]
The proposed solution - setting test environment to node - for "Jest did not exit one second after the test has run completed." warning (shown on the first screenshot) seems not to be fixing it in general case. In that particular example it can be fixed with `afterAll(() => {
  mongoose.connection.close()
})`.
I'm also attaching screenshot from the exercises section where very similar piece of text is given so I suppose that something in 4b supertest section got accidentally replaced.
Anyway, it seems strange so I'm sharing this to have the course stuff informed.

![Screen Shot 2021-01-12 at 04 14 20](https://user-images.githubusercontent.com/58368055/104256655-a7111000-548c-11eb-9932-38d1031665b5.png)
![Screen Shot 2021-01-12 at 04 13 39](https://user-images.githubusercontent.com/58368055/104256591-8fd22280-548c-11eb-9b24-3217af951761.png)

**Comment by mluukkai** [comment]
fixed in 2022 material
