### ISSUE TITLE
Contributing to project - Missing information

### ISSUE THREAD

**Issue by lmgaero** [fullstack-hy2020/fullstack-hy2020.github.io#1120]
Hi everyone, 

I'm taking the FullStack course on my own and noticed that it's an absolutely amazing project so I decided to contribute with the spanish translation, however, I didn't found any information about how to contribute. 

I forked the project but I don't know if I have to work in the spanish-translation, the FixingTranslations (both of them several commits behind source) or directly in the source branch.

I will really appreciate any advice on this. Best regards!

**Comment by mluukkai** [comment]
You're right. We shall resolve this soon. The plan is to get Spanish translation officially released 15th March when the 2021 edition launches

**Comment by Kaltsoon** [comment]
@lmgaero, please check #1164 if you are still interested in contributing
