### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by fom78** [fullstack-hy2020/fullstack-hy2020.github.io#1131]
Hello
I believe that where it says: 
> Create a Heroku application with the command heroku create, commit your code to the repository and move it to Heroku with command git push heroku main.
> 
> If everything went well, the application works:

More information should be added on how to do it, it is not clear what to do, it should explain the step

1. Download the Heroku CLI
2. `$ heroku login` Execute the command to login to heroku
3. `$ cd myAppCloned`  go to the directory of my appClonada:\ 
**Deploy the app**
4. `$ heroku create` create de App
5. `$ git push heroku main`  deploy our code
6. `$ heroku ps: scale web = 1` Ensure that at least one instance of the app is running
7. `$ heroku open` open the website

 [Source from Heroku](https://devcenter.heroku.com/articles/getting-started-with-nodejs?singlepage=true)
Thanks!

**Comment by mluukkai** [comment]
There is a link to heroku documentation and that should be enought
