### ISSUE TITLE
Broken link in Part 6a, the section on "Pure functions, immutable"

### ISSUE THREAD

**Issue by Jakedalus** [fullstack-hy2020/fullstack-hy2020.github.io#1138]
In the following text:

"The application seems to be working, but the reducer we have declared is bad. It breaks the **_basic assumption_** of Redux reducer that reducers must be pure functions."

"Basic assumption" links to here, which is currently a 404 page: https://github.com/reduxjs/redux/blob/master/docs/basics/Reducers.md#handling-actions

**Comment by mluukkai** [comment]
fixed in 2022 edition
