### ISSUE TITLE
React.FC doens't provide any benefits from cra docs.

### ISSUE THREAD

**Issue by sahilrajput03** [fullstack-hy2020/fullstack-hy2020.github.io#1148]
Remove React.FC thing from course.
Source: https://github.com/facebook/create-react-app/pull/8177

**Comment by sahilrajput03** [comment]
Saying so, coz below two components are much same and the latter one is more simpler, verbose and self-explanatory:

=> from above same issue i.e., https://github.com/facebook/create-react-app/pull/8177 :
const C1: React.FC<CProps> = (props) => { }
const C2 = (props: CProps) => {};//Equally good, and more simpler and verbose.

Thanks.

**Comment by Kaltsoon** [comment]
Thanks, this is fixed
