### ISSUE TITLE
Ex. 10.6, unclear instruction about using the prop 'component' instead of 'to' for Link navigation

### ISSUE THREAD

**Issue by fcole90** [fullstack-hy2020/fullstack-hy2020.github.io#1151]
In [10.6](https://fullstackopen.com/en/part10/react_native_basics#exercises-10-6-10-7) I'm confused about what's being asked.

> Users should be able to navigate between the two views by pressing the tabs (hint: use the [Link](https://reacttraining.com/react-router/native/api/Link) component and its [component](https://reacttraining.com/react-router/native/api/Link/component-func) prop).

However, the prop `component` doesn't seem to be necessary for navigation, rather for having some effects, like using some touchable component for changing opacity (e.g. `TouchableOpacity`). In fact, the necessary prop, in this case, would be `to`. So, I'm not sure if the exercise actually wanted us to do something more. Do we need to mimick a [material-design Tab](https://codesandbox.io/s/cbn97?file=/demo.js), eventually by using the `TouchableWithoutFeedback` we added in exercise [10.4](https://fullstackopen.com/en/part10/react_native_basics#exercises-10-4-10-5), which was not used so far?

**Comment by Kaltsoon** [comment]
It depends on the implementation. My first idea was that the implementation would be something like:

```javascript
const AppBarTab = ({ children, ...props }) => {
  return (
    <TouchableWithoutFeedback {...props}>
       {/* bunch of other components */}
    </TouchableWithoutFeedback >
  );
};

const AppBar = () => {
  return (
    <View>
      <ScrollView horizontal>
        <Link to="/" component={AppBarTab}>Repositories</Link>
        <Link to="/sign-in" component={AppBarTab}>Sign in</Link>
      </ScrollView>
    </View>
  );
};
```

But the implementation could also be e.g:

```javascript
const AppBarTab = ({ children, ...linkProps }) => {
  return (
    <Link {...linkProps}>
       {/* bunch of other components */}
    </Link >
  );
};

const AppBar = () => {
  return (
    <View>
      <ScrollView horizontal>
        <AppBarTab>Repositories</AppBarTab>
        <AppBarTab>Sign in</AppBarTab>
      </ScrollView>
    </View>
  );
};
```

So, perhaps the hint should simply be about the `Link` component?

**Comment by fcole90** [comment]
I think that perhaps the hint on `Link` alone can be enough. I'm not sure what you want to achieve in your first example, I can only think you want to remove the _highlight_ animation provided automatically by `TouchableHighlight` but still be able to use `onPress`, is it so?

In my case, I mimicked a Material Design tab and highlighted the selected tab, but still, I used the default component to keep the _highlight_, and my `onPress` is passed as a prop to `TouchableHighlight` (the default for `component`)

```jsx
const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: Constants.statusBarHeight,
    backgroundColor: theme.colors.bgDark,
    ...theme.shadow
  },
  tabLink: {
    paddingVertical: 14,
    paddingHorizontal: 10,
    marginBottom: 1
  },
  tabLinkSelected: {
    borderBottomWidth: 3,
    borderBottomColor: 'white',
    
  },
  tabLinkText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textOnDark,
    textTransform: 'uppercase'
  },
  tabLinkTextSelected: {
    color: 'white'
  }
});

const TabLink = ({title, to, setSelected, selection}) => (
  <Link to={to} onPress={() => {setSelected(to);}} >
    <View style={[
      styles.tabLink,
      selection === to && styles.tabLinkSelected
    ]}>
      <Text style={[
        styles.tabLinkText,
        selection === to && styles.tabLinkTextSelected
      ]}>{title}</Text>
    </View>
  </Link>
);

const AppBar = ({initialSelection}) => {
  const [selectedTab, setSelectedTab] = useState(initialSelection);

  return (
    <View style={styles.container}>
      <ScrollView horizontal>
        <TabLink selection={selectedTab} setSelected={setSelectedTab} to='/' title='Repositories' />
        <TabLink selection={selectedTab} setSelected={setSelectedTab} to='/sign-in' title='Sign In'/>
      </ScrollView>
    </View>
  );
};
```

![image](https://user-images.githubusercontent.com/1292230/108723682-3817e400-752d-11eb-9c8d-d8b8bf4eca59.png)

**Comment by Kaltsoon** [comment]
I think the point of the first implementation is that it's not tight to the `Link` component. In the upcoming exercises there will be a "Sign out" tab which is not a link to a route, instead you just want to attach an `onPress` callback to the tab. In the first implementation this is pretty easy to implement:

```javascript
<Link to="/" component={AppBarTab}>Repositories</Link>
<AppBarTab onPress={handleSignOut}>Sign out</AppBarTab>
```

But there are of course other ways to handle this.
