### ISSUE TITLE
8.22 unclarity

### ISSUE THREAD

**Issue by cdrbbt** [fullstack-hy2020/fullstack-hy2020.github.io#1159]
The exercise is:

_8.22 Up to date cache and book recommendations
If you fetch the book recommendations with GraphQL, ensure somehow that the books view is kept up to date. So when a new book is added, the books view is updated at least when a genre selection button is pressed.
When new genre selection is not done, the view does not have to be updated._

The wording here seem really confusing, the starting sentence  _If you fetch the book recommendations with GraphQL_ seems to be not relevant since the task is about the book view. 

The task asks that when a book is added that the books view be updated at least when a genre is selected. However 8.10 already makes sure that the book view is updated after each book is added.

The intent of the exercise is unclear

**Comment by mluukkai** [comment]
you are right, I made the fix. It is now

_If you did the previous exercise, that is fetch the books in a genre with GraphQL,_ 

8.10 might ensure the correct behavior, it depends how you have done it
