### ISSUE TITLE
Looking for contributors for the Spanish translation 🇪🇸

### ISSUE THREAD

**Issue by Kaltsoon** [fullstack-hy2020/fullstack-hy2020.github.io#1164]
We are looking for contributors who could maintain the existing Spanish translation for the material. At the moment contributions to the Chinese translation are handled so that there's [a fork](https://github.com/RichardStark/fullstack-hy2020.github.io) of this repository, which accepts pull requests for the Chinese translations (the "Propose changes to material" link in the material leads to the fork). The maintainer of the fork (@RichardStark) validates the pull requests, merges them to the fork, and creates a pull request to this repository every now and then (once a week or so). 

We are looking for a person who could maintain this kind of workflow. If you are interested, let us know, by contacting me through Telegram (my username is kalleilv).

---

The fork for the Spanish translation is here: https://github.com/sebastiantorres86/fullstack-hy2020.github.io. The _Proponer cambios al material_ link in the material no points to the fork. Happy translating! 🇪🇸

**Comment by MalbonaGenio** [comment]
Hi! I can help with translation too.

**Comment by davorpa** [comment]
Hi.

I see in website that translators are needed but fork is outdated (500 commits behind)

How to proceed if I want collaborate?

**Comment by foreact** [comment]
I'm in

**Comment by sebaguzman13** [comment]
I ll be glad to help with this

**Comment by mikeminem** [comment]
I can collaborate in the Spanish section!
Just let me know how can I participate!

**Comment by quantosh** [comment]
Hi @Kaltsoon I'd be delighted to help out on an open source training project

**Comment by Wil89** [comment]
Hi, @Kaltsoon I'll be delighted to help this amazing project

**Comment by pepiyu** [comment]
Hello @Kaltsoon ! If you still need help with the Spanish translation, count me in!

**Comment by Rub4l1to** [comment]
Hi @Kaltsoon, just let me know how I can help you 🙋‍♂️

**Comment by MechiRamella** [comment]
👋 Hi @Kaltsoon, 
I would like to help you to translate the documentation from English to Spanish!

**Comment by Suyay-V** [comment]
Hi! I would love to collaborate on this project.

**Comment by FranciscoAlvarezRaineri** [comment]
Hi! I can see that the work here is not over. I would like to help you out with this!

**Comment by alexg1t** [comment]
I also would like to help on this. :)

**Comment by vickiavola** [comment]
I would like to contribute with translations from English to Spanish

**Comment by fedengarcia** [comment]
I would like to contribute with translations from English to Spanish

**Comment by apardavila** [comment]
Hi! I would like to contribute to this project. I am an English into Spanish and Galician translator with a strong interest for IT. Let me know if you still need help.

**Comment by maxtdev** [comment]
Hi! I'm native Spanish speaker, I can help with the translation if it's needed.

**Comment by mluukkai** [comment]
All the contributions are most welcome! Just start doing the pull requests! The most urgent thing to fix would be part0a, I think there is still some old dates in the Spanish version. Same is with the faq

**Comment by YordanSoares** [comment]
Hi everyone! 👋

I would like to start contributing with the Spanish translations. However, I have a couple of questions before starting on this:
1. Do you have a Spanish glossary for translations? Something like [this](https://translate.wordpress.org/locale/es/default/glossary/). 
2. Also, is there a progress tracking anywhere to claim translation that are not being doing by any other contributor?

**Comment by JoseAMedina** [comment]
Hi! Wherever you need, I'm ready to help !

**Comment by DiegoDimuro** [comment]
Hi! I would love to collaborate on this 🧙🏻‍♂️
