### ISSUE TITLE
Part 2d: `export default { ... }`

### ISSUE THREAD

**Issue by akauppi** [fullstack-hy2020/fullstack-hy2020.github.io#1232]
*Writing in English since it seems to be the trend here.*

```
export default { 
  getAll: getAll, 
  create: create, 
  update: update 
}
```

The sample code shows this in multiple places. After seeing it a few times I noticed the `default`.

It obviously works, but blurs the distinction between default export and named exports. Is the reason that the author doesn’t want to add complexity, at this point of the course, or is it just by accident?

Since ESM code in the wild uses named exports (without the `default`) in such cases, I would suggest the course do the same. Can make a PR if the author sees this the same. No guarantees on functionality, though, since I’m only reading the course, at this point.

**Comment by mluukkai** [comment]
Named exports are coming in a bit later part of the course. The reason for using default export is to limit the complexity so will not change it at this point. I might consider the change for next year's edition.
