### ISSUE TITLE
Part 5 > d E2E test problem

### ISSUE THREAD

**Issue by kayraberktuncer** [fullstack-hy2020/fullstack-hy2020.github.io#1250]
The notes added after we write and run our tests are not improtant: true, so they do not appear on the resulting page and our tests return an error.

As a solution I added the following to my code:
````javascript
it('other of those can be made important', function () {
   **cy.contains('show all').click()**
    cy.contains('second note').parent().find('button').as('theButton')
    cy.get('@theButton').click()
    cy.get('@theButton').should('contain', 'make not important')
})
and
it('a new note can be created', function () {
    cy.contains('new note').click()
    cy.get('input').type('a note created by cypress')
    cy.contains('save').click()

    **cy.contains('show all').click()**
    cy.contains('a note created by cypress')
})
````

The codes I enclose in asterisks allow us to pass the test.

I would like to put it as pr but, the codes [here](https://github.com/fullstack-hy/part2-notes/tree/part5-11) need to be edited too.

I will be glad if you are interested. Have a nice working day.

**Comment by mluukkai** [comment]
fixed in 2022 edition
