### ISSUE TITLE
Part 5c: Add information about @testing-library/jest-dom

### ISSUE THREAD

**Issue by akrabdev** [fullstack-hy2020/fullstack-hy2020.github.io#1258]
![image](https://user-images.githubusercontent.com/37980706/115439344-c4cdde00-a20e-11eb-95e9-af7eabaa5672.png)

In my opinion it would be better here to briefly mention why we are adding  testing-library/jest-dom along with testing-library/react

like: jest-dom library add more jest matchers to make testing DOM more convenient

**Comment by mluukkai** [comment]
done for 2022 edition
