### ISSUE TITLE
Wrong reference in part 7e - Useful libraries and interesting links

### ISSUE THREAD

**Issue by j-tesla** [fullstack-hy2020/fullstack-hy2020.github.io#1275]
In [part 7e - Useful libraries and interesting links](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/source/src/content/7/en/part7e.md#useful-libraries-and-interesting-links), the link [https://applibslist.xyz/](https://applibslist.xyz/) is not relevant.

**Comment by mluukkai** [comment]
has been removed
