### ISSUE TITLE
Desktop spanish 2a: no padding in the exercises section

### ISSUE THREAD

**Issue by NahuelDev** [fullstack-hy2020/fullstack-hy2020.github.io#1288]
![image](https://user-images.githubusercontent.com/17348111/117211618-a3085580-adcf-11eb-945c-26089ef567e5.png)
on english:
![image](https://user-images.githubusercontent.com/17348111/117211746-c7fcc880-adcf-11eb-9dff-13d40627396e.png)

**Comment by mluukkai** [comment]
fixed
