### ISSUE TITLE
5c - About the use of fireEvent in place of userEvent

### ISSUE THREAD

**Issue by p4nu** [fullstack-hy2020/fullstack-hy2020.github.io#1297]
Testing of forms would be easier if `userEvent` are used in tests in place of `fireEvent`. Is this left like this for educational purposes? Can I use `userEvent`s in assignments if `fireEvent` is used to mimic user actions?

More info:
https://testing-library.com/docs/ecosystem-user-event

**Comment by augustjanse** [comment]
For the record, the library author [recommends using userEvent over fireEvent where possible](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-testing-libraryuser-event).

**Comment by mluukkai** [comment]
done in 2022 edition
