### ISSUE TITLE
Part 7d - provided heroku app is down

### ISSUE THREAD

**Issue by damevi** [fullstack-hy2020/fullstack-hy2020.github.io#1351]
The url from https://fullstackopen.com/en/part7/webpack#development-and-production-configuration does not work

<img width="980" alt="image" src="https://user-images.githubusercontent.com/57729449/121473128-7ba23b00-c9c2-11eb-903f-7161c560b270.png">

**Comment by spamegg1** [comment]
@damevi I don't think that's supposed to be accessible directly through the browser like that. You use it in the backend, in `webpack.config.js`. 
```js
const backend_url = argv.mode === 'production'
    ? 'https://blooming-atoll-75500.herokuapp.com/api/notes'
    : 'http://localhost:3001/notes'
```
I have this script in `package.json`:
```js
"build": "webpack --mode=production",
```
Then I run `npm run build`. Then I open the `build/index.html` file. This will fetch the notes from that address and display them (although there are currently no notes in there.)
![index](https://user-images.githubusercontent.com/4255997/121476044-dd68a200-c9ce-11eb-9f0c-25275d283fb4.png)

I hope my understanding is correct here, maybe @mluukkai can confirm.

**Comment by damevi** [comment]
well I believe it should, the similar heroku app I've made earlier in the course works just fine 

https://murmuring-falls-88583.herokuapp.com/api/notes/

moreover, I got the app from part7 up and running and the get request gets aborted, hence it shows 0 notes
<img width="384" alt="image" src="https://user-images.githubusercontent.com/57729449/121476550-1ac93180-c9c7-11eb-90be-6866d412f10a.png">

**Comment by spamegg1** [comment]
Hmm OK... The frontend at https://blooming-atoll-75500.herokuapp.com is also failing if I try to save notes, with 503. I suppose you're right then.

**Comment by mluukkai** [comment]
is taken care of in 2022 edition
