### ISSUE TITLE
Part 2C, Cors prevents completion of 2.17

### ISSUE THREAD

**Issue by AM-thedev** [fullstack-hy2020/fullstack-hy2020.github.io#1356]
When sending a HTTP DELETE request this error is returned:

Access to XMLHttpRequest at 'localhost:3001/persons/' from origin 'http://localhost:3000' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

The only viable option beyond reading part 3 and working backwards is to disable the appropriate security setting in Chrome.

**Comment by mluukkai** [comment]
I do not believe CORS is the _real_ reason
