### ISSUE TITLE
React State Best Practices

### ISSUE THREAD

**Issue by meikkismakke** [fullstack-hy2020/fullstack-hy2020.github.io#1370]
The model answer on '1.14*: anecdotes step3' suggests to have three states, but only two is really needed. 'MostVotes' can be expressed as a function of current 'votes'.

Changing from three to two states would jive better with the best practices as suggested in the React documentation [Thinking in React] (URL:https://reactjs.org/docs/thinking-in-react.html).  Identifying the minimal (but complete) representation of UI state can help keep code DRY.

I understand it's a minor edit, but wanted to call out in case it helpful for others!

**Comment by mluukkai** [comment]
has been fixed in 2022 edition
