### ISSUE TITLE
Changes to the Part-8 Course

### ISSUE THREAD

**Issue by arbob** [fullstack-hy2020/fullstack-hy2020.github.io#1396]
There are many changes to Apollo playground and GraphQL resolvers and how they work.
1. The landing page for http://localhost:4000/graphql no longer has a playground. **Instead, there is a button** which redirects us to Apollo Sandbox on their website. (Also a note should be added to disable ad-blocker otherwise the sandbox will give error).
2. In the "Object within an object" chapter of GraphQL-Server section, the result is shown without using a custom address resolver. But, it doesn't work without custom resolver. I have checked everything from typo to indentations, but it doesn't work. However, when I add the custom resolver, it works. I don't know if this is a bug or a new feature in GraphQL, but it's something worth exploring into.

**Comment by JoseDRamirezM** [comment]
Responding to 2. yo HAVE to write a custom resolver because otherwise it would use the default resolver (wich is mentioned  earlier) 

` js
Person: {
  / ...
    address: (root) => root.address,
  }
`
address field is not a value, it's an object

**Comment by arbob** [comment]
I was talking about the material of the course. Like you said, the material needs to have a custom resolver for addresses.

**Comment by mluukkai** [comment]
fixed in 2022 edition
