### ISSUE TITLE
PubSub support ended in Apollo 3

### ISSUE THREAD

**Issue by arbob** [fullstack-hy2020/fullstack-hy2020.github.io#1403]
As seen on their documentation:
`Beginning in Apollo Server 3, subscriptions are not supported by the "batteries-included" apollo-server package.`
[Subscriptions in Apollo Server](https://www.apollographql.com/docs/apollo-server/data/subscriptions/)

Kindly update the material as mentioned above.

**Comment by tsensei** [comment]
For anyone having difficulties with this, you can just 
`
npm install graphql-subscriptions
`

And import it in index.js

`
const { PubSub } = require("graphql-subscriptions")
`

**Comment by JoseDRamirezM** [comment]
> For anyone having difficulties with this, you can just
> `npm install graphql-subscriptions`
> 
> And import it in index.js
> 
> `const { PubSub } = require("graphql-subscriptions")`

This will also work with WebSockets to listen for subscriptions? I ended up rewriting most of the server part.

**Comment by Kaltsoon** [comment]
We have now instructed to use apollo-server version 2. Let us know if there are issues with that version.

**Comment by mluukkai** [comment]
fixed
