### ISSUE TITLE
Part 3b: Deploying app to internet - PUT 404

### ISSUE THREAD

**Issue by TiceWise** [fullstack-hy2020/fullstack-hy2020.github.io#1411]
While deploying the front-end and back-end combined, I got an error on toggling the 'important button' on and off; the response was "Cannot PUT /api/notes/4".

I've been writing code along with the course examples. And also cross-checked them with the versions on the course github. I've found the bug but was a bit surprised that I ran into this, so I might have missed something (if so, please let me know!).

The bug from my point of view: The notes front-end 'update' in the 'Note Service', uses axios.put. But in the index.js of the back-end, only get root, get all notes, get note id, delete note id and post note are defined, no 'put'. 

My solution: added app.put to index.js of the back-end, something like:

```
app.put('/api/notes/:id', (request, response) => {
  const body = request.body

  if (!body.content) {
    return response.status(400).json({
      error: 'content missing'
    })
  }
  const updatedNote = {
    content: body.content,
    important: body.important,
    date: body.date,
    id: body.id
  }

  notes = notes.map(note => note.id === body.id ? updatedNote : note)

  response.json(updatedNote)
})
```

**Comment by mluukkai** [comment]
It is actually not a bug. The material mentions

_And the frontend works! However, the functionality for changing the importance of notes has not yet been implemented to the backend._

The put operation is not actually implemented at all in part 3. It is done in the exercise 3.17 for the phone book app.

**Comment by TiceWise** [comment]
Ah missed that sentence, sorry about that. Thanks!
