### ISSUE TITLE
Add a theory section about the lifecycle of functional components into part 1 or 2

### ISSUE THREAD

**Issue by Starle21** [fullstack-hy2020/fullstack-hy2020.github.io#1412]
**This course has been amazing, you guys rock!**

**Positive**
I especially appreciate the incremental step by step structure building from the basics to more complex, clear connections and easy-to-follow explanations. I can't appreciate it enough :-)

**Negative**
In the beginning - parts 1 and 2 - I've found it hard to grasp React's rendering process and lifecycle of functional components and hooks just from React's documentation. Since it's still new, the explanations focused a lot on class components not just there, but all over the internet.
Telegram group helped - [**this article**](https://overreacted.io/a-complete-guide-to-useeffect/) came in highly recommended, it would be great to link it in the course material.

**My suggestion**
I suggest that you include a short theory section at the end of part 1 or 2 to explain this a bit and include the mentioned link.

**Comment by mluukkai** [comment]
Quite a bit more about the component lifecycle will soon be in the parts 1 and 2
