### ISSUE TITLE
Part 8e Subscriptions on the server obsolete

### ISSUE THREAD

**Issue by Starle21** [fullstack-hy2020/fullstack-hy2020.github.io#1431]
Current Apollo Server 3 doesn't natively support subscriptions, so the instructions in 8e on setting up subscriptions on the server don't apply anymore. Please upgrade that part or instruct to downgrade to Apollo 2.

**Comment by Kaltsoon** [comment]
Thanks! We have now instructed people to either use apollo-server 2 or follow Apollo Server's documentation as a quick fix. We'll update the part later.
