### ISSUE TITLE
Mongoose 6.0.0 find() method 

### ISSUE THREAD

**Issue by PedroYanezE** [fullstack-hy2020/fullstack-hy2020.github.io#1464]
I'm having trouble with mongoose's find() method on part 3.c "Fetching objects from the database".
In the part where we have to implement:

```
Note.find({}).then(result => {
  result.forEach(note => {
    console.log(note)
  })
  mongoose.connection.close()
})

```

I get the following error:

```
TypeError: cursor.toArray is not a function
```

I did some research and found [this page](https://mongoosejs.com/docs/api.html#model_Model.find), with that I tried to implement the fetching functionality like this:

```
Note.find({}, function (err, docs) 
{
    if(err) return err

    docs.forEach(note => console.log(note))
    mongoose.connection.close()
});
```

But got the following error:

```
    MongoInvalidArgumentError: Method "collection.find()" accepts at most two arguments
```

Interestingly enough, when I try findOne() like this:

```
Note.findOne({'content':'HTML is easy'}, 'content date', function(err, note){
    if(err) 
    {
        console.log(err)
        return err
    }

    console.log(note)
    mongoose.connection.close()
})
```

I do get a response:

```
{
  _id: new ObjectId("6126af0678428afcbb654851"),
  content: 'HTML is easy',
  date: 2021-08-25T20:58:46.014Z
}
```

I think the problem might be that the current version of mongoose changed the way find() worked compared to when the course was written, because when I try to connect like the course says:

```
mongoose.connect(url, { useNewUrlParser: true, useUnifiedTopology: true, useFindAndModify: false, useCreateIndex: true })
```

I get the following error:

```
MongoParseError: options usefindandmodify, usecreateindex are not supported
```

So I suspect the issue may be with the "useFindAndModify" option.
I've been trying to fix this all day, so I hope somebody knows a solution. Thanks in advancement!

**Comment by altanaldeniz** [comment]
It seems reverting back to 5.13.8 is the only solution. I tried to follow mongoose 6.x docs to solve the issue but unfortunately their solutions did not work for me.

**Comment by mluukkai** [comment]
2022 edition uses mongoose ^6.1.7 and no issues with this
