### ISSUE TITLE
Part 10b: eslint reporting errors in webpack.config.js, but everything runs fine

### ISSUE THREAD

**Issue by tera-si** [fullstack-hy2020/fullstack-hy2020.github.io#1489]
In [part 10b routing](https://fullstackopen.com/en/part10/react_native_basics#routing), we were instructed to install

    npm install react-router-native

and

    npm install @expo/webpack-config --save-dev

and then create a `webpack.config.js`, with the provided code, in the root directory.

I did all that, and eslint reports four errors in `webpack.config.js`.

The first and second are to do with,

    const path = require('path');
                 ^
                'require' is not defined

    const createExpoWebpackConfigAsync = require('@expo/webpack-config');
                                         ^
                                        'require' is not defined

The third has to do with

    module.exports = async function(env, argv) {...
    ^
    'module' is not defined

And the final error has to do with

    include: [path.join(__dirname, 'node_modules/react-router-native')],
                        ^
                        '__dirname' is not defined

However, if I run `npm start`, everything is going fine, I can run the app on web browsers, emulators, and the expo mobile app. No build errors nor runtime errors.

I suspect the cause is that, eslint assumed `webpack.config.js` would be run on the client side, instead of the expo framework. In other words, eslint is not aware of the expo environment.

Here are the project dependencies so far:

      "dependencies": {
        "expo": "~40.0.0",
        "expo-status-bar": "~1.0.3",
        "react": "16.13.1",
        "react-dom": "16.13.1",
        "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
        "react-native-web": "~0.13.12",
        "react-router-native": "^5.2.1"
      },
      "devDependencies": {
        "@babel/core": "^7.9.0",
        "@babel/eslint-parser": "^7.15.4",
        "@expo/webpack-config": "^0.15.0",
        "eslint": "^7.32.0",
        "eslint-plugin-react": "^7.25.1"
      },

Not sure if I missed any steps from the material tho.

**Comment by Kaltsoon** [comment]
> I suspect the cause is that, eslint assumed webpack.config.js would be run on the client side, instead of the expo framework. In other words, eslint is not aware of the expo environment.

Yeah, this might be it. You can add a `/* eslint-disable */` line at the top of the `webpack.config.js` file to disable the checks for the file.
