### ISSUE TITLE
Part3d: mongoose-unique-validator peer dependency

### ISSUE THREAD

**Issue by ZDGharst** [fullstack-hy2020/fullstack-hy2020.github.io#1494]
I imagine you revitalize this course every semester or so. Mongoose 6.0.0 was recently released (August 24th), and running `npm install mongoose` installs version 6.x.x. 

However, mongoose-unique-validator as instructed to be used for exercise 3.19 is used with Mongoose 5.2.x.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: phonebook-backend@0.0.1
npm ERR! Found: mongoose@6.0.5
npm ERR! node_modules/mongoose
npm ERR!   mongoose@"^6.0.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer mongoose@"^5.2.1" from mongoose-unique-validator@2.0.3
npm ERR! node_modules/mongoose-unique-validator
npm ERR!   mongoose-unique-validator@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I haven't encountered any problems after --force. However, it may be helpful to add a note for other students to use --force or consider if anything else breaks in a future part of the course that perhaps installing an older version of Mongoose might be a better idea.

**Comment by LucasPiedrahita** [comment]
Thanks for reporting this issue and for letting the community know that --force has worked for you, @ZDGharst! 

I just wanted to add that I also encountered this issue and used --force to get around it, but would love to hear from FSO maintainers if there are considerations to make when using --force.

**Comment by mluukkai** [comment]
mongoose-unique-validator no more used in course
