### ISSUE TITLE
Part 2 exercise 2.12 - old version restcountries API 

### ISSUE THREAD

**Issue by toemies** [fullstack-hy2020/fullstack-hy2020.github.io#1507]
In the current version of the REST Countries API (https://restcountries.com/#api-endpoints-v3), population is not provided as a property, yet it is shown as one of the required country parameters to display on screen. Perhaps this can be substituted for a different country statistic, like country area? This way, the newest version of the API can be used

**Comment by mluukkai** [comment]
exercise modified
