### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by vadzimk** [fullstack-hy2020/fullstack-hy2020.github.io#1551]
Search bar not working:

![fullstackopen_search](https://user-images.githubusercontent.com/28674835/138566584-05ebca26-8771-473f-9cf3-531b1ae14d44.gif)
g

**Comment by lorenzojkrl** [comment]
This is only happening when searching in English. Other languages don't have the same problem.

**Comment by akirataguchi115** [comment]
Is this still a problem? Works on my machine :four_leaf_clover: 
If not maybe close the issue?

**Comment by vadzimk** [comment]
looks like it's working now, thanks
