### ISSUE TITLE
11.2 Suggestion

### ISSUE THREAD

**Issue by imran-pavel** [fullstack-hy2020/fullstack-hy2020.github.io#1557]
When running the tests [this](https://stackoverflow.com/questions/54543063/how-can-i-suppress-the-no-files-matching-the-pattern-message-in-eslint) error may show up ( I am running on Windows ).

'changing single quotes to escaped double quotes' fixes the 'issue'. ( Sebastian Voráč's answer from the link )

Just in case, adding some comment about it in 11.2 may help.

**Comment by mluukkai** [comment]
do not really understand what this is about so will close
