### ISSUE TITLE
Search option is not available in Spanish

### ISSUE THREAD

**Issue by lorenzojkrl** [fullstack-hy2020/fullstack-hy2020.github.io#1564]
![image](https://user-images.githubusercontent.com/18583152/139525936-83523a8b-3ad5-4254-82c2-ab393613649a.png)

Is this feature not implemented?

**Comment by Kaltsoon** [comment]
Spanish is not included https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/source/gatsby-config.js#L46. Creating the search index increases the build time so we'll need to consider which languages are added.
