### ISSUE TITLE
Hyperlink anchor to action-creators broken

### ISSUE THREAD

**Issue by akirataguchi115** [fullstack-hy2020/fullstack-hy2020.github.io#1571]
In parts 6ab there are hyperlinks to action creators but since the anchor #action-creators doesn't exist anymore it's redirected here: https://redux.js.org/tutorials/fundamentals/part-2-concepts-data-flow

maybe this could be a better substitute: https://read.reduxbook.com/markdown/part1/04-action-creators.html ?

**Comment by mluukkai** [comment]
changed in 2022 edition
