### ISSUE TITLE
Part4 module.exports explained

### ISSUE THREAD

**Issue by jeansibelius** [fullstack-hy2020/fullstack-hy2020.github.io#1577]
Hi!

Thank you for creating this great material that has been fun to work on.

One thing that could perhaps be clarified in the material is the difference in usage of `module.exports` between a direct assignment vs. named assignment (assigning an object to it). For example [here](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/92f395328ee5333008c44e8af4c567d4c318d8e9/src/content/4/en/part4a.md?plain=1#L165).

In practice, what is the difference between the following to examples?
```
// Example 1
module.exports = {
  something,
}
```
and  
```
// Example 2
module.exports = something
```

For example with Routes() using `module.exports = { notesRouter, }` instead of `module.exports = notesRouter` gives an error `TypeError: Route.use() requires a middleware function but got an object`. So there are situations where using the named assignment/object-style exporting will break the app.

**Comment by mluukkai** [comment]
shall be clarified in 2022 edition
