### ISSUE TITLE
Incorrect object null check in pictures of code example in part 9c

### ISSUE THREAD

**Issue by TamarixGallica** [fullstack-hy2020/fullstack-hy2020.github.io#158]
Part 9c contains a section on [proofing requests](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/source/src/content/9/en/part9c.md#proofing-requests) where parseComment function implements a check as `if (!comment || !isString(comment))`.

However, both picture [28](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/source/src/content/images/9/28.png) and [29](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/source/src/content/images/9/29.png) show the same check implemented as `if (comment || !isValidString(comment))`. The missing exclamation mark causes the check to throw an error if comment is not null.

Pictures should be updated to match the code presented in text to show a proper null check and prevent people running into issues when creating their own implementations based on the pictures.

**Comment by mluukkai** [comment]
Thanks for pointing this out, those are now fixed
