### ISSUE TITLE
Feature request: Add dark mode to the website

### ISSUE THREAD

**Issue by reazulislam13** [fullstack-hy2020/fullstack-hy2020.github.io#1605]
Hi,
I've noticed there's no _dark mode_ option in **fullstackopen.com**. So I'm proposing to add the _dark mode_ feature in the website. I think it'll be a useful addition to the overall experience for the learners.

Thanks!

**Comment by akirataguchi115** [comment]
Have you tried out [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) yet with the course material?

**Comment by reazulislam13** [comment]
> Have you tried out [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) yet with the course material?

Thanks. It works great!
