### ISSUE TITLE
Part6 addition: Redux Toolkit 

### ISSUE THREAD

**Issue by medic-code** [fullstack-hy2020/fullstack-hy2020.github.io#1637]
Ive been going through the Redux tutorials on the official website and noticed that they're advocating for using Redux Toolkit which simplifies much of the content of the Part6 Redux chapter. I realise it's still probably important to understand all the bits currently covered in the section, but I wonder whether this should be an extra section to setting up and dealing with Redux toolkit. 

The benefits to it are that it already has redux thunks, redux devtools extension as part of the package. It simplifies the action creators and provides a more intuitive way to may async data calls, simplifies creating the store and provides some error handling for accidentally mutating the state. In fact it actually allows you to create mutating state which gets converted to an immutable state via Immer. 

See below for further details

https://redux.js.org/tutorials/fundamentals/part-8-modern-redux - Overview of getting set up

https://redux-toolkit.js.org/usage/usage-guide - Takes you through how it simplifies redux.

Would be interested to hear your thoughts.

**Comment by mluukkai** [comment]
done in 2022 edition
