### ISSUE TITLE
Incorrect example response in 9.16

### ISSUE THREAD

**Issue by TamarixGallica** [fullstack-hy2020/fullstack-hy2020.github.io#164]
Exercise 9.16 instructs students to expand Patient interface by adding an array for entries. Attached image [38a](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/source/src/content/images/9/38a.png) shows an empty array of entries should be included in the response. However, this seems to require additional measures such as adding an empty array to each patient's JSON object or adding the array when creating the response.

I believe additional steps should be documented or image updated to reflect the actual expected response.

**Comment by Kaltsoon** [comment]
> Create an endpoint /api/patients/:id that returns all of the patient information for one patient, **including the array of patient entries that is still empty for all the patients**

I think the desired end result is explained quite well. The implementation itself can be chosen freely.
