### ISSUE TITLE
translate into russian

### ISSUE THREAD

**Issue by vladthelittleone** [fullstack-hy2020/fullstack-hy2020.github.io#165]
good day! tnx for your work. 
can we translate this course into russian?
we can fork the repository and add a `ru` folder.
also we can write here about our progress.

**Comment by vladthelittleone** [comment]
fork repo: https://github.com/vectree/fullstack-hy2020.github.io

PROGRESS:

- [ ] part 0
  - [ ] General info
  - [ ] Fundamentals of Web apps
- [ ] part 1
  - [ ] Introduction to React
  - [ ] JavaScript
  - [ ] Component state, event handlers
  - [ ] A more complex state, debugging React apps

**Comment by mluukkai** [comment]
no progress here for a long time so will close this
