### ISSUE TITLE
Multiple React Apps in Part1 Nested Weirdly

### ISSUE THREAD

**Issue by PansFortress** [fullstack-hy2020/fullstack-hy2020.github.io#167]
In the first part of the course, we're asked to create a new react app, part1

> npx create-react-app part1
> cd part1

Towards the end of the unit, we're recommended to create multiple create-react-apps in the following folder structure:

```
part0
part1
   courseinfo
   unicafe
   anectodes 

```

Is this intended? If so, then at this point of the lecture, we'll have react apps nested within a react app.

**Comment by mluukkai** [comment]
The apps are not nested, just in different directories under the main repository

**Comment by PansFortress** [comment]
Thanks for the fast reply. I might have misunderstood the wording. The first thing we do is create a part1 directory which contains a react app:

>npx create-react-app part1
>cd part1

Source: (https://fullstackopen.com/en/part1/introduction_to_react)
Screenshot:
<img width="782" alt="Screen Shot 2020-03-20 at 1 08 51 PM" src="https://user-images.githubusercontent.com/5084409/77202660-fc1e0880-6aab-11ea-99a2-14bc138c9f0b.png">


After we navigate into part1, we're asked to create a new react-app to solve the problems:
> npx create-react-app courseinfo


We now have a react app (courseinfo) nested inside a react app (part1).
