### ISSUE TITLE
Part 7a - React Router - npm i react-router-dom uses v6, breaking example

### ISSUE THREAD

**Issue by merriman-xyz** [fullstack-hy2020/fullstack-hy2020.github.io#1675]
If you follow the instructions, you will get an error that the `<Switch>` component doesn't exist.

This is because `react-router-dom` version 6 replaces `<Switch>` with a `<Routes>` components. Another difference is that <Route> takes components as props instead of as children. 

The example should go from 

```jsx
<Switch>
  <Route path="/notes">
    <Notes />
  </Route>
  <Route path="/users">
    <Users />
  </Route>
  <Route path="/">
    <Home />
  </Route>
</Switch>
```
to 

```jsx
<Routes>
  <Route path="/notes" element={<Notes />} />
  <Route path="/users" />
  <Route path="/" />
</Routes>
```

From official docs @ https://reactrouter.com/docs/en/v6/getting-started/tutorial

```jsx
  <BrowserRouter>
    <Routes>
      <Route path="/" element={<App />} />
      <Route path="expenses" element={<Expenses />} />
      <Route path="invoices" element={<Invoices />} />
    </Routes>
  </BrowserRouter>
```

---

A [StackOverflow post noting the issue](
https://stackoverflow.com/questions/70266560/src-app-js-attempted-import-error-switch-is-not-exported-from-react-router#:~:text=If%20you%20accidentally%20updated%20react-router-dom%20to%20version%206,components.%20Swap%20the%20Switch%20for%20the%20Routes%20component).

**Comment by merriman-xyz** [comment]
`useHistory` is also replaced by the `useNavigate` hook

**Comment by mluukkai** [comment]
Will be fixed in 2022 edition. Now I added a note to use version 5 of RR.
