### ISSUE TITLE
Part 8b sample code for "Named queries and variables" section not working

### ISSUE THREAD

**Issue by smth324** [fullstack-hy2020/fullstack-hy2020.github.io#1701]
The page renders correctly like in the pictures but whenever I hit the "close" button the state of the person changes to null which returns me to the main page for a split second but for some reason the useEffect hook fires again which brings me back to the single person view. I am not sure why this is happening. I am also sure that I set the second parameter of the effect hook to be result. here is my code. Also it would be nice to include the imports in the picture in the course. Please forgive me if I am making a mistake.

import { useState, useEffect } from "react"
import { useLazyQuery, gql } from "@apollo/client"

const FIND_PERSON = gql`
  query findPersonByName($nameToSearch: String!) {
    findPerson(name: $nameToSearch) {
      name
      phone 
      id
      address {
        street
        city
      }
    }
  }
`

const Persons = ({ persons }) => {
  const [getPerson, result] = useLazyQuery(FIND_PERSON) 
  const [person, setPerson] = useState(null)

  const showPerson = (name) => {
    getPerson({ variables: { nameToSearch: name } })
  }

  useEffect(() => {
    if (result.data) {
      setPerson(result.data.findPerson)
    }
  }, [result])
  if (person) {
    return(
      <div>
        <h2>{person.name}</h2>
        <div>{person.address.street} {person.address.city}</div>
        <div>{person.phone}</div>
        <button onClick={() => setPerson(null)}>close</button>
      </div>
    )
  }
  
  return (
    <div>
      <h2>Persons</h2>
      {persons.map(p =>
        <div key={p.name}>
          {p.name} {p.phone}
          <button onClick={() => showPerson(p.name)} >
            show address
          </button> 
        </div>  
      )}
    </div>
  )
}

export default Persons

**Comment by mluukkai** [comment]
fixed in 2022 edition
