### ISSUE TITLE
MongoDB Atlas setup has changed a bit from what's described in the course material

### ISSUE THREAD

**Issue by jolammi** [fullstack-hy2020/fullstack-hy2020.github.io#1703]
As I created a database to MongoDB Atlas today, the menus were a bit different than what was described in the material. The databsae creation was still totally doable using common sense, but I just thought to notify that the screenshots and text don't completely match the MongoDB Atlas website anymore. 

For example database user creation:

Materials:
![image](https://user-images.githubusercontent.com/22539418/147413838-dea78750-fba3-43ff-868c-98bf34575378.png)

Actual website:
![image](https://user-images.githubusercontent.com/22539418/147413857-f2c3895e-75eb-4df9-923b-cf2a594e2f86.png)

But yeah, this is probably not the most crucial thing to change.

**Comment by mluukkai** [comment]
fixed in 2022 edition

**Comment by gentilmente** [comment]
it changed again  (TT)
it seems not to be "allow access to everyone" anymore.
<img width="1010" alt="Captura de Pantalla 2022-10-12 a la(s) 16 44 19" src="https://user-images.githubusercontent.com/993201/195434024-7719020d-536e-49b8-ad18-7e19b2fe1477.png">
