### ISSUE TITLE
GraphQL & React Native problem

### ISSUE THREAD

**Issue by jjaine** [fullstack-hy2020/fullstack-hy2020.github.io#1722]
By the [changelog of apollo-client](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#apollo-client-354-2021-11-19):

> Since Apollo Client v3.5.0, CommonJS bundles provided by @apollo/client use a .cjs file extension rather than .cjs.js, so Node.js won't interpret them as ECMAScript modules. While this change should be an implementation detail, it may cause problems for the Metro bundler used by React Native, whose resolver.sourceExts configuration does not include the cjs extension by default.

The suggested fix needed an addition of **`"jsx"`** to make the `.jsx` files working:

```
const { getDefaultConfig } = require("metro-config");
const { resolver: defaultResolver } = getDefaultConfig.getDefaultValues();
exports.resolver = {
  ...defaultResolver,
  sourceExts: [
    ...defaultResolver.sourceExts,
    "jsx",
    "cjs",
  ],
};
```

**Comment by Kaltsoon** [comment]
Thanks, this should be fixed now!
