### ISSUE TITLE
Part 4.7 does not exist

### ISSUE THREAD

**Issue by Brokenchin** [fullstack-hy2020/fullstack-hy2020.github.io#1726]
In the page:
https://fullstackopen.com/osa4/kayttajien_hallinta

There is a link that should take to part 4.7 in the notes-backend. However such a branch does not exists.

Broken link is in the text below:
Sovelluksen tämänhetkinen koodi on kokonaisuudessaan GitHubissa, branchissä part4-7.

**Comment by mluukkai** [comment]
will be fixed in 2022 edition
