### ISSUE TITLE
Part 5d - Using Cypress with WSL2

### ISSUE THREAD

**Issue by kpav33** [fullstack-hy2020/fullstack-hy2020.github.io#1729]
Users that are using WSL2 for completing exercises must perform some additional configuration to be able to use Cypress and finish exercises from 5.17. to 5.22.

Cypress docs on how to set up WSL2 to be able to use Cypress - [https://docs.cypress.io/guides/getting-started/installing-cypress#Windows-Subsystem-for-Linux](https://docs.cypress.io/guides/getting-started/installing-cypress#Windows-Subsystem-for-Linux)
A blog post on how to do the set up - [https://nickymeuleman.netlify.app/blog/gui-on-wsl2-cypress](https://nickymeuleman.netlify.app/blog/gui-on-wsl2-cypress)

The second link (blog post) is more in depth, because for Cypress to work with WSL2 you need to install some additional dependencies to Linux. I set up Cypress on my WSL2 by using both guide (obviously they overlap with the same instructions for the most part).

I think that it would be useful to add a simple heads up message to the Cypress part to just notify people that if they are using WSL2, they will need to do some extra steps before they can use it and provide either one or both of this two links, which explain how to perform the set up. Like there is a message about potential issues with the updated mongoose-unique-validator in part 4c, there could be a similar message about potential issues with Cypress, if you are developing with WSL2.

**Comment by mluukkai** [comment]
fixed in 2022 edition
