### ISSUE TITLE
Part 1c  saving index.js file reloads the contents of the page automatically

### ISSUE THREAD

**Issue by ksajan** [fullstack-hy2020/fullstack-hy2020.github.io#1753]
In the lesson about page re-rendering, it was said that if you change content and save content in index.js won't re-render automatically but it is not the case anymore as I was doing the course it is getting re-render whenever I save the content. Probably the recent changes in react have something to do about this or I am too dumb to understand this. Anyone if you know about this please confirm. Thank you!

**Comment by mluukkai** [comment]
yes, this has changed now. will be taken into account in 2022 edition
