### ISSUE TITLE
Part 6 content updated without notice, horrible experience for worldwide students

### ISSUE THREAD

**Issue by ThePridestalker** [fullstack-hy2020/fullstack-hy2020.github.io#1787]
Hello!

I started the fullstackopen course in August 2021, in my spare time, to learn React in my free time after work. Like so, I'm still doing it, at part 6.12 to be exact, and suddenly I find myself using redux toolkit createSlice out of nowhere. I checked the next exercises, and saw that the code snippets have different code than what it was supossed to be at the last snippets I had seen, so I went back and saw that this part https://fullstackopen.com/en/part6/many_reducers#redux-toolkit for example is completely new, and the exercises from 6.9 on are completely different. Not even a message in the page, a warning indicating dates of renewal of content, or a symbol indicating that the exercise or content was recently added.

I wasn't planning on sending the solutions for the certificate anyways, but this is frustrating nonetheless.

What am I suppose to do now? download the repo and find the old exercises in the older versions of the files?

**Comment by mluukkai** [comment]
sorry for that 😢 . the previous version had officially ended 10th Jan. but for exercises the deadline of 2021 version is 1st March so I should have postponed the update of part 6 or at least communicate that better. 

you can still access the old content here https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/tree/f4c3bc2dda05b035d3369e780108391df8158b83/src/content/6/en
