### ISSUE TITLE
Part 8 broken links

### ISSUE THREAD

**Issue by akirataguchi115** [fullstack-hy2020/fullstack-hy2020.github.io#1811]
There seems to be plentyful of broken links in part 8 that lead here: https://github.com/fullstack-hy2020/graphql-phonebook-backend/tree/part8-5

However the correct(?) link is this: https://github.com/FullStack-HY/graphql-phonebook-backend although this makes no sense as FullStack-HY is apparently the Finnish-only version of the course.

**Comment by mluukkai** [comment]
hy2020 is the correct one

**Comment by akirataguchi115** [comment]
This https://github.com/fullstack-hy2020/graphql-phonebook-backend/tree/part8-5 says 404 on my end
