### ISSUE TITLE
How to build this project locally

### ISSUE THREAD

**Issue by JabSYsEmb** [fullstack-hy2020/fullstack-hy2020.github.io#1854]
Is it possible to request a tutorial on how to build this project locally, `127.0.0.1`? or to ship a docker image that is set up with all required packages to run this project inside it? 

Thanks in advance.

**Comment by tenkirin** [comment]
This project requires Node v10 to run. Higher versions of Node are not supported as one of dependencies `node-sass` is specified as [`^4.11.0`](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/1d1e66b8de3fd7e39041b9ca7cb41691fc3dd9b0/package.json#L33)(for now, Mar 15, 2022). So make sure you are using the right node version before `npm install`. Maybe you need to use `nvm` to downgrade your Node. See also [this issue](https://github.com/sass/node-sass/issues/2662#issuecomment-495531675) for more details. Hope this can be helpful.

**Comment by JabSYsEmb** [comment]
Thank you @tenkirin!

I did downgrade Node to v10 and it worked.
