### ISSUE TITLE
Suggestion: introduce cypress react component tests

### ISSUE THREAD

**Issue by marcindulak** [fullstack-hy2020/fullstack-hy2020.github.io#1877]
I may be beneficial to introduce https://docs.cypress.io/guides/component-testing/introduction#What-is-Component-Testing. Please see examples in the (private) repository https://github.com/marcindulak/fullstackopen2022

Additionally mentioning testing as early as possible, preferably in part1, may allow students
to develop more robust code from the beginning.

**Comment by marcindulak** [comment]
Playwright also supports now component testing https://playwright.dev/docs/test-components, however it seems only with typescript react https://github.com/microsoft/playwright/issues/14156.

**Comment by mluukkai** [comment]
not planned
