### ISSUE TITLE
part8-7 branch doesn't exist

### ISSUE THREAD

**Issue by enkeipy** [fullstack-hy2020/fullstack-hy2020.github.io#1901]
At the end of "[Subscriptions on the server](https://fullstackopen.com/en/part8/fragments_and_subscriptions#subscriptions-on-the-server)" there is a link for a backend code on branch [part8-7](https://github.com/fullstack-hy2020/graphql-phonebook-backend/tree/part8-7). Apparently this branch had been overwritten because the presented code matches part8-6 branch and doesn't seem to follow code in "Subscriptions on the server".

**Comment by mluukkai** [comment]
fixed
