### ISSUE TITLE
Suggested improvements to index.js in the example solution of part3

### ISSUE THREAD

**Issue by mabouguerra** [fullstack-hy2020/fullstack-hy2020.github.io#191]
- The cropped image of the script doesn't show the full `morgan` function call (including the newly defined `body` token).
- When using `findByIdAnUpdate`, mongoose doesn't automatically run validation, so a configuration object [needs](https://github.com/blakehaswell/mongoose-unique-validator#find--updates) to be passed: `{ runValidators: true, context: 'query' }`. Because, if we don't we will be able to update the number of a person with less than 8 digits.
-   We should have probably added an unknown endpoint error handler as well? and if so, we should then catch errors of the first two route handlers.
- In the third route handler, I assume the intention was to name the variable `person` instead of `note`.

**Comment by mluukkai** [comment]
fixed in 2022 edition
