### ISSUE TITLE
Modern JavaScript versions are incorrectly called ES<Edition> instead of ES20XY

### ISSUE THREAD

**Issue by thetric** [fullstack-hy2020/fullstack-hy2020.github.io#195]
Modern JavaScript versions are incorrectly called by their edition, for example ES6, ES7 or ES10 instead of their official name [ES2015](http://www.ecma-international.org/ecma-262/6.0/index.html), [ES2016](http://www.ecma-international.org/ecma-262/6.0/index.html) and [ES2019](http://www.ecma-international.org/ecma-262/10.0/index.html). The book "You don't know JS" [recommends using the official names](https://github.com/getify/You-Dont-Know-JS/blob/1d80dca433619f29d0afd27aea0fdb0ce2cde5a6/get-started/ch1.md#whats-with-that-name) too:

> Don't use terms like "JS6" or "ES8" to refer to the language. Some do, but those terms only serve to perpetuate confusion. "ES20xx" or just "JS" are what you should stick to.

**Comment by jxofficial** [comment]
Hi, can I take this issue?

**Comment by Kaltsoon** [comment]
I will close this issue because this isn't really a major issue. If you want, feel free to open a pull request to provide an improved version
