### ISSUE TITLE
Wrong code highlighting and wrong code provided in part 8b react-graphql

### ISSUE THREAD

**Issue by poonamsagar** [fullstack-hy2020/fullstack-hy2020.github.io#197]
I have encountered below two issues while learning mutations in Graphql-React app:-
1. In image below an extra bit of code is provided after onError handler as highlighted in image below
![image](https://user-images.githubusercontent.com/24935685/77846095-40717d00-71ff-11ea-894d-dada902eb669.png)

2. Additionally as shown in image below, there is new code in app.js for error handling while mutation, most of which, is highlighted by lighter shade but there is some missed new code not being highlighted.
![image](https://user-images.githubusercontent.com/24935685/77846201-110f4000-7200-11ea-9ae6-9209b7ecc9bc.png)

**Comment by mluukkai** [comment]
fixed in 22 edition
