### ISSUE TITLE
Part 5a: add a note that persisting session information in localStorage is not secure

### ISSUE THREAD

**Issue by thetric** [fullstack-hy2020/fullstack-hy2020.github.io#198]
In [Part 5a](https://fullstackopen.com/en/part5/login_in_frontend) the JWT, user name and name are stored in the `localStorage` so the user is still authenticated after a page reload. This suggests the reader to be a "best practice". This method should *never* be used in production due to security risks:

From the [OWASP Cheat Sheet Series - HTML 5 Security](https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#local-storage):

> - [...] any authentication your application requires can be bypassed by a user with local privileges to the machine on which the data is stored. Therefore, it's recommended not to store any sensitive information in local storage.
[...]
> - A single Cross Site Scripting can be used to steal all the data in these objects, so again it's recommended not to store sensitive information in local storage.
> A single Cross Site Scripting can be used to load malicious data into these objects too, so don't consider objects in these to be trusted.
> - Do not store session identifiers in local storage as the data is always accessible by JavaScript. Cookies can mitigate this risk using the httpOnly flag.
> [...]

From the [OWASP Cheat Sheet Series - Session Management](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#security-risks):

> In general, secure or sensitive data should not be stored persistently in browser data stores as this may permit information leakage on shared systems. Because the Web Storage mechanisms are APIs, this also permits access from injected scripts, making it less secure than cookies with the httponly flag applied. While a case could be made for storing workflow specific data in sessionStorage for use by that specific tab/window across reloads, the Web Storage APIs should be treated as insecure storage. Because of this, if a business solution requires the use of the localStorage or sessionStorage to store sensitive data, such a solution should encipher data and apply replay protections. Due to the potential to access Web Storage APIs via an XSS attack, session identifiers should be stored using non-persistent cookies, with the appropriate flags to protect from insecure access (Secure), XSS (HttpOnly) and CSRF issues (SameSite).

A note should be added to clarify that the persistence of JWTs or session information in general in localStorage/sessionStorage is not recommended in production applications.

**Comment by Kaltsoon** [comment]
I commented on the issue here: https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/issues/766. Feel free to continue the discussion in that issue
