### ISSUE TITLE
Misleading information in two different sections

### ISSUE THREAD

**Issue by reazul64** [fullstack-hy2020/fullstack-hy2020.github.io#1987]
According to the prerequisites section (Part 0 > General info > Prerequisites), participants are expected to have **mastery** of the Git version management system.

But in the about course section (About course > General), it's written that participants are expected to know the **basics** of working with the Git version management system.

![Screenshot1](https://user-images.githubusercontent.com/57848079/165467006-fda90ed6-f77e-4c4b-bf26-b578d20e9d1f.png)

![Screenshot2](https://user-images.githubusercontent.com/57848079/165467018-5fe181b5-90a9-4bbb-a614-15c54f6da1a9.png)

Knowing the basics is not the same as mastery. So I think one of the sections needs to be updated to reflect the prerequisites of Git version management system.

**Comment by mluukkai** [comment]
fixed. mastery is perhaps a too strong requirement.
