### ISSUE TITLE
I have encountered some problems while studying part10c.

### ISSUE THREAD

**Issue by ZZZCNY** [fullstack-hy2020/fullstack-hy2020.github.io#1993]
My `useQuery()` doesn't work properly, when I run in web browser it loads repositories properly, but on android emulator, `loading` always true and `networkStatus` always 1.

This is my code:

```js
const useRepositories = () => {
  const [repositories, setRepositories] = useState()
  const { loading, error, networkStatus } = useQuery(GET_REPOSITORIES, {
    onCompleted: data => setRepositories(data.repositories),
    notifyOnNetworkStatusChange: true,
  })

  useEffect(() => {
    console.log('loading =', loading)
    console.log('networkStatus =', networkStatus)
  }, [loading])

  return { repositories, loading, error }
}
```

I tried using `pollInterval` and modifying `fetchPolicy` to `no-cache` or `network-only`, both to no avail. But in the process of modifying `fetchPolicy`, there is a certain probability that `loading` will become false and `networkStatus` will become 7. When I keep commenting and uncommenting, it has the probability to run properly, but normal operation is always fails.

**Comment by ZZZCNY** [comment]
After my attempts to downgrade apollo client to 3.5.10, it works fine.

```
"@apollo/client": "^3.5.10"
```

**Comment by ZZZCNY** [comment]
#1994

**Comment by Kaltsoon** [comment]
This sounds weird, is there any related issues in the Apollo Client repository?

**Comment by Kaltsoon** [comment]
That issue is closed so I'm closing this as well. Please reopen if the problem persists.
