### ISSUE TITLE
Issue with DiagnosisSelection component

### ISSUE THREAD

**Issue by marioseg** [fullstack-hy2020/fullstack-hy2020.github.io#1997]
https://github.com/fullstack-hy2020/patientor/blob/main/src/AddPatientModal/FormField.tsx#L58

The line 117 --> setFieldValue(field, selectedDiagnoses);

Is not working as expected. What I did to solve the issue was to change it for ---> setFieldValue(field, [...data]);

:)

**Comment by mluukkai** [comment]
this will be fixed tomorrow with the "new patientor"
