### ISSUE TITLE
Incorrect Link to install chrome extension JSONView

### ISSUE THREAD

**Issue by AkshitChugh787** [fullstack-hy2020/fullstack-hy2020.github.io#1998]
Correct Link - https://chrome.google.com/webstore/detail/jsonview/gmegofmjomhknnokphhckolhcffdaihd

Under Part 2/Getting Data from Server/The Browser as a runtime environment

**Comment by lucitemple** [comment]
Is it an incorrect link, or incorrect text?

- Current link goes to [JSONVue](https://chrome.google.com/webstore/detail/jsonvue/chklaanhfefbnpoihckbnefhakgolnmc) which has over 1 million users, last update December 2021, and was originally forked from JSONView, I think to improve use in Chrome.
- [JSONView](https://chrome.google.com/webstore/detail/jsonview/gmegofmjomhknnokphhckolhcffdaihd) has only 80,000 users, last update Jan 2021, originally for Firefox, has some chrome compatibility.

At a glance they both look like they would do the job. Do you have an opinion on which one would be best to include in fullstack open (do we need to change the text to match the existing link, or change the link to match the existing text.).

**Comment by mluukkai** [comment]
text was incorredt, fixed now
