### ISSUE TITLE
Add Dark mode to the website

### ISSUE THREAD

**Issue by utkarsh1311** [fullstack-hy2020/fullstack-hy2020.github.io#2010]
Currently, the website is only available to view in light mode. It makes reading the site's content at night difficult.
Addition of a dark mode will make it easier to browse through the site at night time.

**Comment by rikurauhala** [comment]
Hello Utkarsh. You might want to look into [Dark Reader](https://github.com/darkreader/darkreader). Works great with the course material!

**Comment by utkarsh1311** [comment]
Hey @rikurauhala . Thank you for the suggestion. I am already using Dark Reader , but I think a built-in dark mode should be available for the website.
