### ISSUE TITLE
Mongoose ^6.3.4 

### ISSUE THREAD

**Issue by manuelbasanta** [fullstack-hy2020/fullstack-hy2020.github.io#2026]
Part 3B - MongoBD section: Connecting to mongoDB with the latest version of mongoose (^6.3.4 ) is not working if the course code is used. The current code is the following:

```
mongoose.connect(url)

const noteSchema = new mongoose.Schema({
  content: String,
  date: Date,
  important: Boolean,
})

const Note = mongoose.model('Note', noteSchema)

const note = new Note({
  content: 'HTML is Easy',
  date: new Date(),
  important: true,
})

note.save().then(result => {
  console.log('note saved!')
  mongoose.connection.close()
})
```

As I said I am using `"mongoose": "^6.3.4"` and I had to await te response of `mongoose.connect(url)` for it to work like so:
```
mongoose.connect(url).then(() => {
    const noteSchema = new mongoose.Schema({
        content: String,
        date: Date,
        important: Boolean,
    })
    
    const Note = mongoose.model('Note', noteSchema)
    
    const note = new Note({
        content: 'test',
        date: new Date(),
        important: true,
    })
    
    note.save().then(result => {
        console.log('note saved!')
        mongoose.connection.close()
    })
})
```

If I am not mistaken and the problem relies on the current version of mongoose then the solution would be to update the course contents using this latest version. I'd be glad to help

**Comment by vimode** [comment]
I am aware this issue is old but I think this issue can be closed as it was fixed in #2031
