### ISSUE TITLE
Part 5b: use the official way to customize ESLint

### ISSUE THREAD

**Issue by thetric** [fullstack-hy2020/fullstack-hy2020.github.io#203]
In [Part 5b](https://fullstackopen.com/en/part5/props_children_and_proptypes#e-slint) a custom ESLint configuration is created that tries to override the one supplied by `create-react-app`. This approach is not quite optimal: the editor integration and the npm `lint` task work, but `create-react-app` does not pick up it up, thus not showing the lint warnings in the terminal and in-browser lint output.

The official and experimental way to customize the ESLint config is described in [the CRA docs](https://create-react-app.dev/docs/setting-up-your-editor/#experimental-extending-the-eslint-config):

> [...] It is now possible to extend the base ESLint config by setting the `EXTEND_ESLINT` environment variable to `true`. [...]
> 
> Note that any rules set to `"error"` will stop the project from building.
> 
> There are a few things to remember:
> 
> 1. We highly recommend extending the base config, as removing it could introduce hard-to-find issues.
> 2. When working with TypeScript, you'll need to provide an overrides object for rules that should only target TypeScript files.
> 
> In the below example:
> 
> - the base config has been extended by a shared ESLint config,
> - a new rule has been set that applies to all JavaScript and TypeScript files, and
> - a new rule has been set that only targets TypeScript files.
> 
> ```json
> {
>   "eslintConfig": {
>     "extends": ["react-app", "shared-config"],
>     "rules": {
>       "additional-rule": "warn"
>     },
>     "overrides": [
>       {
>         "files": ["**/*.ts?(x)"],
>         "rules": {
>           "additional-typescript-only-rule": "warn"
>         }
>       }
>     ]
>   }
> }
> ```

**Comment by mluukkai** [comment]
mention added to 2022 material
