### ISSUE TITLE
Part 10B - react-router-native issues

### ISSUE THREAD

**Issue by jcmsmith** [fullstack-hy2020/fullstack-hy2020.github.io#2032]
First of all, this isn't in any way the fault of the course but there's an issue with the current version (5.3.2) of react-router-native that gets installed by default when following the instructions: remix-run/react-router/issues/8880. I had to remove node_modules and package-lock.json, change the version in package.json to 5.3.3, and re-run npm install in order for it to work properly (just trying to upgrade it failed and gave me lots of errors about mismatched dependencies etc). It probably won't be an issue for long, but I figured I'd mention it because it gave me quite a headache.

Secondly, the example code (from [here](https://fullstackopen.com/en/part10/react_native_basics#routing)) does not work:

```
<Routes>        
  <Route path="/" element={<RepositoryList />} exact /> 
  <Route path="*" element={<Navigate to="/" replace />} />      
</Routes>
```

It throws the error "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined". As per v5.reactrouter.com/native/guides, the correct prop is "component" - not element - <Navigate> should be <Redirect>, and <Routes> should probably be <Switch>, I think? I haven't tried that yet so I'm not sure. I ended up with:

```
<Route exact path="/">
    <RepositoryList />
  </Route>

  <Route path="*">
    <Redirect to="/" />
  </Route>
```

Apologies in advance for any formatting (or otherwise) issues, this is my first ever submitted issue on github. I thought about doing a PR to correct the material myself, but I haven't really done any of those yet either! And finally, thanks for all of the free learning!

Edit: 

Okay so after moving forward with the material and being instructed to use the useNavigate hook which didn't work and wasn't in the docs whatsoever, I realized... I was using Version 5, the latest version of react-router is V6, and the latest docs are [here](https://reactrouter.com/docs/en/v6). In my defense, the differences between react-router-dom and react-router-native aren't very well explained by the creators, there's no warning on the V5 page saying that V6 exists, and the [npm listing](https://www.npmjs.com/package/react-router-native) says 5.3.2 is the latest, 5.3.3 is "classic", and 6.3.0 is down in version history... I'm still pretty confused as to what release is actually intended by the authors to be used.

So yeah, I'm glad I didn't do a PR! I'm not entirely sure whether I should be closing this or not, as 5.3.2 is the default-install version but V6 is working fine so far and I can now actually do as the material instructs. I'm just going to leave it as-is.

**Comment by MartinOvington** [comment]
I've had the exact same issue and manually changing the version of react-native-router to 6.3.0 in package.json followed by running "npm install" is the only thing that allowed me to follow the instructions under the "Routing" section on the page without getting an error. I would not have figured this out without looking at your advice, so I think the material needs updating.

**Comment by Kaltsoon** [comment]
There shouldn't be any v5 stuff in the material. Please reopen or open a PR if you have any more such problems.
