### ISSUE TITLE
Consider removing profanities

### ISSUE THREAD

**Issue by ajlakanen** [fullstack-hy2020/fullstack-hy2020.github.io#2167]
https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/6fe11b1f75a2ef34741a3b1e5bb449b96cc6ea6d/src/content/5/fi/osa5c.md?plain=1#L689-L697

**Comment by joshcull3n** [comment]
profanities are a big part of software development tbh

**Comment by yuvaldim** [comment]
Fuck that!

**Comment by Kaltsoon** [comment]
Perhaps we'll need some [PEGI](https://pegi.info/) labels?

![bad-language-black-EN](https://user-images.githubusercontent.com/3078411/184585674-5d4eb1c6-6ea5-4658-8de8-c1a085a55e43.jpeg)
