### ISSUE TITLE
Issue in part2 d -changing the importance of notes

### ISSUE THREAD

**Issue by Aphievel** [fullstack-hy2020/fullstack-hy2020.github.io#2205]
Quoting the material, 
> We can now use the "dollar-bracket"-syntax to add parts to the string that will evaluate JavaScript expressions, e.g. the value of a variable. Note that the quotation marks used in template strings differ from the quotation marks used in regular JavaScript strings

I feel it would be more clear if you tell the student to use backticks in template strings.

> We can now use the "dollar-bracket"-syntax to add parts to the string that will evaluate JavaScript expressions, e.g. the value of a variable. Note that we use backticks in template strings instead of quotation marks used in regular JavaScript strings

**Comment by mluukkai** [comment]
fixed
