### ISSUE TITLE
Heroku removing its free product plans

### ISSUE THREAD

**Issue by yannjor** [fullstack-hy2020/fullstack-hy2020.github.io#2211]
This may affect part 3 of the course. 

https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq

**Comment by vimode** [comment]
True, not just part 3 but I believe heroku is used throughout the course, 

Unfortunately it seems like this news is affecting a lot of bootcamps, courses and projects. 
Many other alternatives are being suggested like fly.io, render.com and some others. 

I hope within few days things will be more clearer and other PaaS providers will try to take provide a relief somehow.

**Comment by mluukkai** [comment]
fly.io now a replacement in all parts but 11, and soon also there
