### ISSUE TITLE
Code block highlighting fails when "*" is in the code block. 

### ISSUE THREAD

**Issue by CakeCrusher** [fullstack-hy2020/fullstack-hy2020.github.io#2227]
Whenever the symbol `*` is in the code block all subsequent highlighting commands fail.
I believe this is related to `gatsby-remark-prismjs`.

Both instances of this issue can be found in [Part 13c](https://fullstackopen.com/en/part13/migrations_many_to_many_relationships) where the `*` of `    glob: 'migrations/*.js',` provokes the issues.

![image](https://user-images.githubusercontent.com/37946988/188288040-8173ffb2-8725-4ac1-ab23-3fdaef0380cc.png)

![image](https://user-images.githubusercontent.com/37946988/188288193-1d318f9b-013c-4a30-850c-bba0761e0872.png)

**Comment by mluukkai** [comment]
fixed
