### ISSUE TITLE
Incorrect image on Part 13c.

### ISSUE THREAD

**Issue by CakeCrusher** [fullstack-hy2020/fullstack-hy2020.github.io#2228]
During this portion of the lesson the many to many relationships was being applied to `/api/users/:id` not `/api/users`.

The image is showing the correct application but on the wrong route.

![image](https://user-images.githubusercontent.com/37946988/188288276-f988b9fc-5e34-43aa-b2d2-18f0cdbc163b.png)

**Comment by mluukkai** [comment]
fixed
