### ISSUE TITLE
Part 8e: Migrate from 'subscriptions-transport-ws' to 'graphql-ws'

### ISSUE THREAD

**Issue by TomRadford** [fullstack-hy2020/fullstack-hy2020.github.io#2240]
As per guidelines on the [Apollo Docs]( https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws), this section should be updated to use [graphql-ws](https://www.npmjs.com/package/graphql-ws).

**Comment by mluukkai** [comment]
done
