### ISSUE TITLE
Part 5d: Cypress setup changed with v10

### ISSUE THREAD

**Issue by laurin-no** [fullstack-hy2020/fullstack-hy2020.github.io#2290]
When setting up Cypress in Part 5d according to the material, I noticed that the mentioned auto-generated files were missing and there were no mentions of the config window that opened. After checking the notes app repository I saw that the instructions are based on version 9 and version 10, which was released in 06/2022 contains some breaking changes: https://docs.cypress.io/guides/references/changelog#10-0-1

Specifically:
> A default configuration file will no longer be auto-generated by Cypress when a configuration file doesn't exist. Instead, you can run cypress open and set up your project with a specific testing type to have this file generated. This allows you to customize the configuration setup by testing-type for the language and dependencies leveraged in your project.

I can look into creating a PR that updates the instructions.

**Comment by mluukkai** [comment]
fixed
