### ISSUE TITLE
Add a chapter on GDPR

### ISSUE THREAD

**Issue by laurin-no** [fullstack-hy2020/fullstack-hy2020.github.io#2315]
When going through Part 7c I noticed that we are [taking Google Fonts into use](https://fullstackopen.com/en/part7/more_about_styles#material-ui), which reminded me of some news stories from earliert this year, when a [German court ruled that this is against GDPR](https://www.theregister.com/2022/01/31/website_fine_google_fonts_gdpr/) because the website owner did not get consent from the user for loading the fonts. Here is a [blog post](https://dev.solita.fi/2022/03/28/embed-google-webfonts.html) with instructions for working around the issue by self-hosting the fonts. Then in the summer of 2022 this caused topic came up in [Austrian national news](https://www.patrickriedl.at/wave-of-lawsuits-in-austria-due-to-use-of-google-fonts/) because a lawyer allegedly sent up to 10.000 cease and desist letters asking for 190 Euros each.

Based on these happenings I would suggest mentioning the issue of loading external assets in light of data privacy rules and I think it could be an interesting or at least a very relevant topic for a new chapter, where relevant parts of GDPR are mentioned and references on further reading. Or maybe there is even some company that wants to cooperate on creating a whole new part on privacy and data protection regulations.

What do you think?

**Comment by vimode** [comment]
I have read debates as to how people should NOT be using the CDN provided by Google Fonts but instead download the google fonts (as its [legally allowed](https://fonts.google.com/knowledge/using_type/self_hosting_web_fonts)) and host it themselves. 

Thank you for sharing this, now I know why. For some reason, I am unable to access that link you provided (solita.fi) but I found [another resource](Thank you for sharing this, ) which has some instructions for self-hosting google fonts.

**Comment by vimode** [comment]
And I totally agree, there has to be note or a warning that when using free fonts via a CDN one should consider self-hosting those to comply with GDPR rules.
