### ISSUE TITLE
part 2a - Refactoring modules using index as a key

### ISSUE THREAD

**Issue by nathaniades** [fullstack-hy2020/fullstack-hy2020.github.io#234]
I realize that these are small code snippets but I feel like it conflicts with the paragraph right before "refactoring modules", which is aptly named "Anti-pattern: array indexes as keys" and emphasizes that such practice should be avoided.

I feel like, for beginners, the rule that array indexes should be avoided must be also followed down to the last snippet, otherwise confusion will ensue.

The following example:
```
const App = ({ notes }) => {
  return (
    <div>
      <h1>Notes</h1>
      <ul>
        {notes.map((note, i) => 
          <li key={i}>
            {note.content}
          </li>
        )}
      </ul>
    </div>
  )
}
```
should become:
```
const App = ({ notes }) => {
  return (
    <div>
      <h1>Notes</h1>
      <ul>
        {notes.map(note => 
          <li key={note.id}>
            {note.content}
          </li>
        )}
      </ul>
    </div>
  )
}
```

And again the example right after:
```
const Note = ({ note }) => {
  return (
    <li>{note.content}</li>
  )
}

const App = ({ notes }) => {
  return (
    <div>
      <h1>Notes</h1>
      <ul>
        {notes.map((note, i) => 
          <Note key={i} note={note} />
        )}
      </ul>
    </div>
  )
}
```

should change into:
```
const Note = ({ note }) => {
  return (
    <li>{note.content}</li>
  )
}

const App = ({ notes }) => {
  return (
    <div>
      <h1>Notes</h1>
      <ul>
        {notes.map(note => 
          <Note key={note.id} note={note} />
        )}
      </ul>
    </div>
  )
}
```

I understand that with these code snippets such issues are of no consequence, but I still believe that it's important to demonstrate best practices as much as possible.

**Comment by mluukkai** [comment]
good point. to be honest I do not even know how the use of index got to the code, perhaps due to an early pull request. will fix this

**Comment by mluukkai** [comment]
thanks for the pr!
