### ISSUE TITLE
Heroku: no free tier, fly.io: credit card needed -> render.com

### ISSUE THREAD

**Issue by manundi** [fullstack-hy2020/fullstack-hy2020.github.io#2348]
Hello!

Since Heroku is ending free tier and fly.io needs a credit card, I did some investigation for free web service offers. render.com seems to do exactly what Heroku does. I suggest to take a look and add as option.

**Comment by mluukkai** [comment]
render.com is likely a good choice for the purposes of parts 0-7. it might not give everything that is needed for parts 11 and 13.

**Comment by lincww** [comment]
Perhaps railway.app is also a good choice however you need some extra (but simple) knowledge on how to deploy.

**Comment by mluukkai** [comment]
will be fixed tomorrow

**Comment by mjrfxci** [comment]
> will be fixed tomorrow

Did you guys fixed the part of use Heroku? I'm struggling with this part, I've trying even with a cpanel option that's mine, but the backend doesn't work. How to solve this please?

**Comment by mluukkai** [comment]
has been fixed already for couple months...
