### ISSUE TITLE
Part 6 - createStore is deprecated

### ISSUE THREAD

**Issue by dev0T** [fullstack-hy2020/fullstack-hy2020.github.io#2367]
First off all, thank you so much for making possible anyone to benefit from the course contents. I already learned many things that I didn't learn in my post-secondary.  It's amazing!

I am now in part 6 and when starting with the exercises I realized that my VSCode pointed out that createStore from Redux is deprecated as of April of 2022. I did a bit of looking around and noticed that this is solved by using Redux-toolkit which is introduced later in the course.

Knowing that, I believe would be great to add a kind of warning so students that get this message are aware that this is something expected and will be dealt with the possibility of using configureStore.

Cheers

**Comment by virusxd521** [comment]
Hi @dev0T , 
thanks for pointing it out. 
as mentioned in the following [Link](https://stackoverflow.com/questions/71944111/redux-createstore-is-deprecated-cannot-get-state-from-getstate-in-redux-ac) , it's ok to use it however a better implementation will be to use redux-toolkit. 
I will try to think about a caveat that will handle this misunderstanding. 

Thanks

**Comment by mluukkai** [comment]
Good point, I shall add a warning there. We use createStore at the beginning for pedagogical reasons since it is easier to start with it. Then when one has a bit familiarity with the redux-philosophy (that is indeed a tricky one for many) it is time to use the real thing.

**Comment by mluukkai** [comment]
there is now mention that we use it for a short while for pedagogical reasons
