### ISSUE TITLE
Concerning Part 7A React Router

### ISSUE THREAD

**Issue by ilanoh** [fullstack-hy2020/fullstack-hy2020.github.io#2400]
There is a problem with this section,

Because if a view is gated to logged user,
Then refreshing the page will call the server but the route associated to the new URL doesn't exists.
So we end-up receiving an error like invalid jwt when it hits this middleware for example.
How can we use react router, and still have it work even when page is refreshed.

Thanks

**Comment by dev0T** [comment]
I avoided this issue by having a conditional that will create different routes depending if the user is authenticated or not. However this won't work with useMatch as it needs router to wrap the <App/> component.

**Comment by mluukkai** [comment]
hmm. not sure about this. there is no jwt in use in part 7a
