### ISSUE TITLE
Blog list ~ bloglist inconsistent exercise names

### ISSUE THREAD

**Issue by marcindulak** [fullstack-hy2020/fullstack-hy2020.github.io#2413]
Some examples:

![Screenshot from 2023-01-01 16-00-52](https://user-images.githubusercontent.com/3178318/210175260-1efc31c2-00b0-443e-b551-cb3932254116.png)

![Screenshot from 2023-01-01 15-58-57](https://user-images.githubusercontent.com/3178318/210175270-892bfc9b-2e6a-4d53-a14c-5405cfbc0de9.png)

**Comment by dev0T** [comment]
I believe that in part 4 they are refeering to the bloglist project (which as far as I remember only contains the api), while in part 5 you have the blog list application that consists of a frontend and a backend. It doesn't look inconsistent to me.

**Comment by marcindulak** [comment]
This was just one example, part5 uses different naming conventions as well.

![Screenshot from 2023-01-13 17-51-08](https://user-images.githubusercontent.com/3178318/212374929-306cf1e5-38cc-47d5-b5dd-0534f048790a.png)

**Comment by mluukkai** [comment]
fixed
