### ISSUE TITLE
Storybook is not UI framework. And "connect" is not old because stateless and isolated components are not "old".

### ISSUE THREAD

**Issue by plamenjm** [fullstack-hy2020/fullstack-hy2020.github.io#2414]
(PS: In this issue, I am referring "Full Stack open 2022")

I am new to React world. Initially I enjoyed this course a lot. The first pages are very detailed, step by step, small steps - perfect for me. Thank you.

Now, looking at the whole course as one piece, it feels there is a lot for improving.

---
1. In part 7-c:
> Other UI frameworks... "storybook"...

Storybook is not UI framework. Right?
Storybook helps you with right workflow and good habbits - helps you to start the building from ground.
Like, first build and test the components in isolation. Then use and the components in your projects and reuse them in other projects.

---
2. The reason for my comments (the drop that spilled the cup) is in part 6-d:
> To finish this part we will look into another OLDER and more complicated way to use Redux, the "connect" function provided by react-redux.

In contrast to:
> So far, we have created isolated stateless components-–great for Storybook, but ultimately not helpful until we give them some data in our app.

Quoted from here (check it, it is short but looks good): https://storybook.js.org/tutorials/intro-to-storybook/react/en/get-started/

So, building stateless and isolated components is not "old". It is good and useful for code sharing. Actually "connect" is helping to use isolated components inside the specific environment of your project.

---
3. Just few NPM trends. I am new to Storybook as well:
"@material-ui/core vs @storybook/react vs material-ui vs storybook"
https://npmtrends.com/@material-ui/core-vs-@storybook/react-vs-material-ui-vs-storybook
![image](https://user-images.githubusercontent.com/56994434/210224870-a7d0bbbb-4107-405d-a030-505afc8a5526.png)

**Comment by dev0T** [comment]
Yes, storybook isn't a UI Framework but a tool. 7.c could be fixed by changing the list title to "Other UI frameworks and Tools". This isn't a big issue though.

>So, building stateless and isolated components is not "old". It is good and useful for code sharing. Actually "connect" is helping to use isolated components inside the specific environment of your project.

Your interpretation was wrong. It is saying that using connected components is old because it is. Redux in general is old as newer projects will unlikely use it over the context API from React. Old doesn't mean it is bad, it just means that there are newer and better alternatives.

**Comment by plamenjm** [comment]
@dev0T Is it wrong interpretation?

> To finish this part we will look into another older and more complicated way to use Redux, the connect function provided by react-redux.

What the "connect" function does? It takes already connected component and gives you stateless component.

Anyway. I am not native English speaker.

---

> Yes, storybook isn't a UI Framework but a tool

The "fix" is probably simple... But, looks like, it is a good tool. By npm trends it is as good as Meterial UI.

**Comment by mluukkai** [comment]
storybook is now removed from the list
