### ISSUE TITLE
11.10 (fly.io) is failing because webpack is a dev dependency

### ISSUE THREAD

**Issue by nosecreek** [fullstack-hy2020/fullstack-hy2020.github.io#2495]
The instructions for 11.10 (or actually the section which prepares us for 11.10 on fly.io) create an error when attempting to deploy to Fly.io. The issue is that webpack is a dev dependency, but the build process only installs production dependencies. So, when it gets to the build step (`npm run build`) it fails because webpack is not installed. I was able to fix this by changing this line in my Dockerfile `RUN npm install && npm run build` to `RUN npm install --production=false && npm run build`

I'm not 100% sure if this is the best way to do it, or perhaps if webpack should instead be installed as a production dependency instead?

**Comment by lonelyotter** [comment]
Same problem.

**Comment by mluukkai** [comment]
fixed
