### ISSUE TITLE
Typo in part 0b under HTTP GET section

### ISSUE THREAD

**Issue by bumpylumps** [fullstack-hy2020/fullstack-hy2020.github.io#2510]
Proposing a typo fix from :  "The chain of events caused by opening the page https://studies.cs.helsinki.fi/exampleapp on a browser 
-->form the following [sequence diagram](https://www.geeksforgeeks.org/unified-modeling-language-uml-sequence-diagrams/):"

To: The chain of events caused by opening the page https://studies.cs.helsinki.fi/exampleapp on a browser -->from the following [sequence diagram](https://www.geeksforgeeks.org/unified-modeling-language-uml-sequence-diagrams/):

**Comment by mluukkai** [comment]
fixed
