### ISSUE TITLE
The placement of anecdotes form is inconsistent between exercise 6.8 and 6.9

### ISSUE THREAD

**Issue by marcindulak** [fullstack-hy2020/fullstack-hy2020.github.io#2560]
In 6.8, the AnecdoteForm ("create new" form) comes in the middle, in 6.9 (and in the starter code https://github.com/fullstack-hy2020/unicafe-redux, which currently has no starter code), at the end.

![Screenshot from 2023-02-13 19-08-09](https://user-images.githubusercontent.com/3178318/218538663-7025d9e4-70b4-4f2f-b202-2febd7aa43a0.png)

![Screenshot from 2023-02-13 19-07-32](https://user-images.githubusercontent.com/3178318/218538692-bfde63f3-fca1-4051-8784-26b25fb77e83.png)

**Comment by mluukkai** [comment]
the code changed

**Comment by marcindulak** [comment]
I think it's this change https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/commit/36e9fe8878f31cc0db07013bd5469cae56f57d01
