### ISSUE TITLE
Part 3b: Outdated link to "Heroku Buildpack for create-react-app"

### ISSUE THREAD

**Issue by cabbachew** [fullstack-hy2020/fullstack-hy2020.github.io#2611]
At the end of the the [Proxy](https://fullstackopen.com/en/part3/deploying_app_to_internet#proxy) section in Part 3b, there is information about deploying frontend code as its own application. 

> In some situations, it may be sensible to deploy the frontend code as its own application. With apps created with create-react-app it is [straightforward](https://github.com/mars/create-react-app-buildpack).

According to the linked repo, 

> After a long, useful run, this buildpack is now at its end of life 🌅
>
> The underlying [static web server buildpack](https://github.com/heroku/heroku-buildpack-static) is deprecated and will not be supported on Heroku-22 or newer stacks.
>
> Please look into using [Next.js](https://nextjs.org/) or [Remix](https://remix.run/) to develop React apps which are deployable using the [Node.js buildpack](https://github.com/heroku/heroku-buildpack-nodejs).

Although deploying a frontend app separately is not the focal point of the lesson, it may be time to either update the link to a currently supported option or to point to a lesson later on where it could be covered in greater depth.

**Comment by mluukkai** [comment]
heroku deprecated
