### ISSUE TITLE
Some exercises don't have titles, just numbers

### ISSUE THREAD

**Issue by marcindulak** [fullstack-hy2020/fullstack-hy2020.github.io#2644]
The exercises 6.20 - 6.24 and 9.14 - 9.19 don't have titles, just numbers. The exercise titles were a human touch element in the course.

There is also the part 13 that is missing exerciese titles, but the titles are lacking consistently there.

![Screenshot from 2023-02-27 19-12-19](https://user-images.githubusercontent.com/3178318/221655723-0393cf0e-4225-46a5-94dd-87c72149761c.png)

![Screenshot from 2023-02-27 19-19-41](https://user-images.githubusercontent.com/3178318/221655740-4e3757f4-faa5-479d-8ab4-af53cec2deb7.png)

**Comment by Overproness** [comment]
I think this is because these exercises are actually a continuation of **some** exercises. And in those **exercises** the name was mentioned. For instance, in the second image that you provided. It even says : 

> This exercise is similar to the one you have already done in Part 1 of the course, but with TypeScript and some extra tweaks. Start off by modifying the contents of.....
