### ISSUE TITLE
Page Chinese translation is incorrect

### ISSUE THREAD

**Issue by Hanschad** [fullstack-hy2020/fullstack-hy2020.github.io#2647]
https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/source/src/content/1/zh/part1b.md

To refer the wrong line below, 'using brackets' is translated to '使用方括号' which makes more sense.

https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/0c9e5bf295ae473b125f0a6418224f09c88a6dd3/src/content/1/zh/part1b.md?plain=1#L184

**Comment by xuyanshi** [comment]
You could create pull requests to fix the errors you found :)
