### ISSUE TITLE
[Part 1 d - Passing Event Handlers] - Revise/Fix code snippet for Button component

### ISSUE THREAD

**Issue by abdulah-khaleel** [fullstack-hy2020/fullstack-hy2020.github.io#2694]
**Issue Reference:** 
Part 1 d: A more complex state, debugging React Apps
Chapter: Passing Event Handlers to Child Components

**Issue Description:** 
A Button component was created instead of previous html button element. However, in the following code snippet within the JSX where the button component was used, the handleClick prop directly called the function instead of using an arrow function, as the screenshot that follows the snippet shows. Each of the component lines in the JSX should read as follows?

      <Button handleClick={() => setToValue(value + 1)} text="increment" />

I believe the snippet as it is might confuse a few as they follow along as it did to me. 

**Screenshot of snippet requiring update:**
![Screenshot 2023-03-06 at 7 02 08 PM](https://user-images.githubusercontent.com/50518543/223134890-cd955880-3c79-416b-a19a-a1b425af244e.png)

**Comment by mluukkai** [comment]
fixed
