### ISSUE TITLE
Part 4.c,  mongoose-unique-validator plugin cannot be installed alongside mongoose v7

### ISSUE THREAD

**Issue by rokasgarmasukis** [fullstack-hy2020/fullstack-hy2020.github.io#2710]
Trying to install it like in the lesson will throw an error. See [https://github.com/mongoose-unique-validator/mongoose-unique-validator/issues/142](url).
I changed to the latest mongoose version 6 `"mongoose": "^6.10.1"` in `package.json` for now.

**Comment by mluukkai** [comment]
added note that you may need to downgrade mongoose
