### ISSUE TITLE
Debugging react: course is using an old version of React Developer Tools

### ISSUE THREAD

**Issue by daattali** [fullstack-hy2020/fullstack-hy2020.github.io#281]
The course is using an old version of the React Developer Tools. I first noticed it when the screenshot in the course looks very different from the current extension I installed today: instead of having a `React` tab in the developer toolbar, now there are two tabs named `Components` and `Profiler`.

The UI has improved a lot, so the following paragraph in the course is no longer true:

> Unfortunately the current version of React developer tools leaves something to be desired when displaying component state created with hooks: 

This is how it looks now:

![image](https://user-images.githubusercontent.com/952340/79145963-90b81580-7d8f-11ea-9b3b-0314ffd6509e.png)

So the text and image in the course should be removed or updated

**Comment by Kaltsoon** [comment]
Thanks for pointing this out! The issue should now be fixed
