### ISSUE TITLE
error: "read ENOTCONN" when viewing certificates

### ISSUE THREAD

**Issue by SadmanYasar** [fullstack-hy2020/fullstack-hy2020.github.io#2876]
![image](https://user-images.githubusercontent.com/67522140/235172760-77463f80-b1d0-483b-bd52-f6fc45e10d94.png)

I have been trying to access my certificates but all are responding to the error as shown in the image. This is probably something related to [deployment](https://github.com/Unitech/pm2/issues/5338).

**Comment by mluukkai** [comment]
fixed
