### ISSUE TITLE
restcountries.com shutting down

### ISSUE THREAD

**Issue by erikstantoncarlson** [fullstack-hy2020/fullstack-hy2020.github.io#2890]
Exercises 2.18-2.20 instruct to use the restcountries.com API, but it is written on the front page that the site is shutting down. An alternative will be needed for these exercises to stay relevant.

**Exercises link:** https://fullstackopen.com/en/part2/adding_styles_to_react_app#exercises-2-18-2-20
**Announcement link:** https://restcountries.com/#shutting-down

> Sadly, I’ll be shutting down the website due to lack of funding. If you want to host it, you’re more than welcome to do so, but for the time being, the website will be down by the end of May.

**Comment by mluukkai** [comment]
there is now a replacement
