### ISSUE TITLE
is it possible to view this offline?

### ISSUE THREAD

**Issue by JunkyardCat** [fullstack-hy2020/fullstack-hy2020.github.io#2950]
Hi if i download the repo will i be able ti view this offline? If so how do i properly view this? All i see are md files for markdown.

**Comment by Celqaz** [comment]
Hi, @JunkyardCat. 
Sure, VS Code and WebStorm support editing and previewing markdown files; you can conveniently view them when you code. 
You could also choose an open-source markdown editor, like [marktext](https://github.com/marktext/marktext), to view the rendered .md files.

**Comment by mluukkai** [comment]
other option is to clone the repo and run it locally, which requires node 10.18
