### ISSUE TITLE
Add a section about template strings in part 1b because part 2b make an assumption that it was already introduced

### ISSUE THREAD

**Issue by daattali** [fullstack-hy2020/fullstack-hy2020.github.io#298]
In the exercises of part 2b it says

> Brief reminder from the previous part: when you are forming strings that contain values from variables, it is recommended to use a template string:

But template strings were never mentioned before. They should probably be mentioned in part 1b that talks about javascript

**Comment by mluukkai** [comment]
template strings now explained in 2b
