### ISSUE TITLE
Part 4 JWT Authorization Header

### ISSUE THREAD

**Issue by TheRealOwenRees** [fullstack-hy2020/fullstack-hy2020.github.io#2982]
In Part 4 d: Token Authentication, the authorization header in the `getTokenFrom` function is shown as `Bearer eyJhbGciOiJIUzI1NiIsInR5c2VybmFtZSI6Im1sdXVra2FpIiwiaW`. In the Postman and REST Client example images, `Bearer` is written all lower case, which causes a vailed JWT validation. I have attached images to show the differences, even though they are clear.

The image examples on Fullstack Open throw a `JsonWebTokenError`.

For clarity, I have tested this using VS Code REST Client plugin, and with PostMan on a Linux Mint 21.1 build.

The fix is clearly to either:
- update the images to show the word `Bearer` spelled with a capital letter, or
- change the `getTokenFrom` function to spell `bearer` all lowercase

I believe that the image update is the best way forward. 

![20e](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/11390760/4d7eff1a-cd82-49a6-910d-053edea1c70a)
![Screenshot from 2023-06-29 09-43-49](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/11390760/8978574a-38e1-40c1-ae9c-c89a815cbda3)
![21e](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/11390760/64b5ebff-b956-4804-bade-0d5a7f3b3574)
![Screenshot from 2023-06-29 09-54-04](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/11390760/7bc62401-1edc-4d03-8843-2850d304dc2f)

**Comment by mluukkai** [comment]
fixed by another commit
