### ISSUE TITLE
Finnish version is missing important info in part 2e 2.20

### ISSUE THREAD

**Issue by kristianka** [fullstack-hy2020/fullstack-hy2020.github.io#2984]
The English version of the page is more detailed and contains crucial information that the weather API key needs to start with ```REACT_APP``` and how to run it from command line on different platforms. Check it out:

https://fullstackopen.com/en/part2/adding_styles_to_react_app#exercises-2-18-2-20
https://fullstackopen.com/osa2/tyylien_lisaaminen_react_sovellukseen#tehtavat-2-18-2-20

**Comment by KartikAroraOfficial** [comment]
Hey, I've noticed this and I'd get started on fixing this soon.
