### ISSUE TITLE
part 6.14 npm run server not able to connect

### ISSUE THREAD

**Issue by JunkyardCat** [fullstack-hy2020/fullstack-hy2020.github.io#3003]
So im doing 6.14 and im not able to connect to localhost:3001/anecdotes when runnung the command npm run server. It just connects endlessly without any sign
The console doesnt have any error or warning. 

Expected: be able to access db.json on the browser

Screenshot
https://imgur.com/a/BJYVpTK

**Comment by mluukkai** [comment]
the project is replaced
