### ISSUE TITLE
Part 1.2: course information, step2

### ISSUE THREAD

**Issue by mjprinso** [fullstack-hy2020/fullstack-hy2020.github.io#301]
Refactor the Content component so that it does not render any names of parts or their number of exercises by itself. Instead, it only renders three Part components of which each renders the name and number of exercises of one part.

```
const Content = ... {
  return (
    <div>
      <Part .../>
      <Part .../>
      <Part .../>
    </div>
  )
}
```
A look at the above code and the explanation given is confusing as the part component is to be called three (3) times but the parts and their exercises are declared in the App component. Can you please share a code snippet of your implementation. 

Here is what I have achieved based on the above, Kindly let me know if that is the intended out put

```
const Part = (props) => {
  return (
    <p>{props.part} - {props.exercises} exercises</p>
  )
}
```

```
const Content = (props) => {
  return (
    <div>
      <Part part={props.part} exercises={props.exercises} />
    </div>
  )
}
```

```
const App = () => {
  const course = 'Half Stack application development'
  const part1 = 'Fundamentals of React'
  const exercises1 = 10
  const part2 = 'Using props to pass data'
  const exercises2 = 7
  const part3 = 'State of a component'
  const exercises3 = 14

  return (
    <div>
      <Header course={course} />
      <Content part={part1} exercises={exercises1} />
      <Content part={part2} exercises={exercises2} />
      <Content part={part3} exercises={exercises3} />
      <Total exercises={exercises1 + exercises2 + exercises3} />
    </div>
  );
}
```

**Comment by daattali** [comment]
@mjprinso unless you're an actual student in @mluukkai 's class, I doubt he'll be able to respond. There are hundreds , if not thousands, of people taking this course, and it will not be feasible for him to dedicate his time to look into individual solutions.

**Comment by mjprinso** [comment]
@daattali Thank you for the feedback.
