### ISSUE TITLE
exercise 5.8: suggested app state not possible?

### ISSUE THREAD

**Issue by bambery** [fullstack-hy2020/fullstack-hy2020.github.io#3032]
[Exercise 5.8](https://fullstackopen.com/en/part5/props_children_and_proptypes#exercises-5-5-5-11) suggests it is possible to need to make some changes so that usernames of blog creators will be shown without a refresh. 

However, in the previous chapter, exercises [4.17 and 4.19](https://fullstackopen.com/en/part4/token_authentication#exercises-4-15-4-23) (not optional) already ensured I would be properly embedding user JSON in blogs upon creation. 

I think 4.17 ensures that the student must embed the username, name, and ID in responses upon blog creation:

> Modify adding new blogs so that when a new blog is created, any user from the database is designated as its creator (for example the one found first). Implement this according to part 4 chapter populate.

 where the [chapter 4 section on "populate"](https://fullstackopen.com/en/part4/user_administration#populate) demonstrates in detail that I will return username, name, and ID under the user:

> Let's also add a suitable population of user information to notes:

```
notesRouter.get('/', async (request, response) => {
    const notes = await Note
        .find({}).populate('user', { username: 1, name: 1 })
    response.json(notes)
})
```

I do not see how to create the problem scenario proposed in exercise 5.8. It seems to me that every student who reaches this point will find this problem is already solved by work from part 4.

**Comment by mluukkai** [comment]
exercise now changed
