### ISSUE TITLE
part 3d does not reference official mongoosejs documentation

### ISSUE THREAD

**Issue by bambery** [fullstack-hy2020/fullstack-hy2020.github.io#3033]
# [part 3d "validation](https://fullstackopen.com/en/part3/validation_and_es_lint)"

> "We notice that the backend has now a problem: validations are not done when editing a note. [The documentation](https://github.com/blakehaswell/mongoose-unique-validator#find--updates) addresses the issue by explaining that validations are not run by default when findOneAndUpdate is executed."

 
problem - "[The documentation](https://github.com/blakehaswell/mongoose-unique-validator#find--updates)" is for a plugin from some random guy (does he develop for mongoose? mongoose-unique-validator seems to be a standalone plugin).  Why is this being referenced as "the documentation"?  Instead, the course should point to standard documentation,
 https://mongoosejs.com/docs/api/model.html#Model.findByIdAndUpdate()
 https://mongoosejs.com/docs/validation.html#update-validators
 
In the second link, it says "Update validators are off by default, you need to specify the 'runValidators' option", which is the information the student should be looking for here.

**Comment by mluukkai** [comment]
will be fixed in the next commit
