### ISSUE TITLE
Part 5 - Cypress Best Practices - Do not select by class / ID

### ISSUE THREAD

**Issue by TheRealOwenRees** [fullstack-hy2020/fullstack-hy2020.github.io#3037]
In relation to **Part 5**:

[Cypress best practices](https://docs.cypress.io/guides/references/best-practices#Selecting-Elements) dictate that we should not be querying elements by their class or ID. 

We should be using `cy.get('[data-cy="submit"]').click()`, with the relevant attribute added to the html. There is an example on their page on how to add the bulk of that as a custom command.

To reflect this in Fullstack Open, one could:

- rewrite the content of the testing module to reflect best practices (lots of work and not a great introduction)
- add an infomation box within the content of the website to explain the best practices (easier and more gentle to the reader)

If this issue is accepted, I am more than happy to write the accompanying content and push as a PR for you to review.

**Comment by mluukkai** [comment]
closing this since the course is moving from cypress to playwright
