### ISSUE TITLE
Part 5a - Example repository needs to be updated with vite config

### ISSUE THREAD

**Issue by 9600bauds** [fullstack-hy2020/fullstack-hy2020.github.io#3082]
Part 5a of the course provides an example repository to use as a base to complete the exercises. The course says this:
>You can use [this application](https://github.com/fullstack-hy2020/bloglist-frontend) from GitHub as the base of your solution. The application expects your backend to be running on port 3003.

I'm assuming this was true before the course was updated to vite, however, that is no longer the case. This new vite repository is not configured for any backend URL or port.

As per part 3b, the way to solve this issue would be to add a proxy in vite.config.js:
https://fullstackopen.com/en/part3/deploying_app_to_internet#proxy

And as such, I think the only change needed would be to add this to vite.config.js to the provided repository:
` server: {
    proxy: {
      '/api': 'http://localhost:3003'
    }
 }`
 However I'm not 100% sure, which is why I made an issue and not a PR

**Comment by mluukkai** [comment]
Yes, this is missing since I assumed that one would run app only locally and use a hardcoded url in the frontend. But yes, could and should be fixed, a PR would be nice!

**Comment by 9600bauds** [comment]
Should there also be a disclaimer warning the user of the default proxy being applied?
