### ISSUE TITLE
Part 1 a Introduction to React - command "npm create vite@latest part1 -- --template react" inputs

### ISSUE THREAD

**Issue by ivaeisaenen** [fullstack-hy2020/fullstack-hy2020.github.io#3099]
Command ```npm create vite@latest part1 -- --template react``` (npm version 6.14.15) will result in question **Select a Framework**:
-Vanilla
-Vue
-React
-Preact
-Lit
-Svelte
-Solid
-Qwik
-Others

And when selected ```React``` it will ask **Select a variant**:
-TypeScript
-TypeScrpt + SWC
-JavaScript
-JavaScript + SWC

Please add instruction note that there might be some selection and correct option

**Comment by mluukkai** [comment]
hmm, in which operating system you are running the command? works in mac and linux

**Comment by ivaeisaenen** [comment]
Operating system is Windows 10 and everything works fine after selecting React and JavaScript. Maybe just add note that there might be a selection menu for some combination of operation systems (Likely windows) and some versions of npm? 

```npm create vite@latest part1 -- --template react```

![Select a Framework](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/83654303/67d4b999-4bf3-436b-a9ab-1c3ec5fabd53)

![Select a Variant](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/83654303/a36fd870-3f14-44bd-bbe0-23c1219a6c7e)

**Comment by mluukkai** [comment]
With npm 6 or earlier the command differs a bit, see https://vitejs.dev/guide/#scaffolding-your-first-vite-project

**Comment by OwaisRaza04** [comment]
cc

**Comment by KartikAroraOfficial** [comment]
Hey, it's been updated and fixed on the site, you can check now.
for finding out your npm version you can try running ```npm --version``` in your terminal.
