### ISSUE TITLE
Part 5: Note App repository branches don't exist.

### ISSUE THREAD

**Issue by dazfz** [fullstack-hy2020/fullstack-hy2020.github.io#3104]
In part 5 (a, d), the branches for versions 5-3 and 5-9 don't exist.
https://github.com/fullstack-hy2020/part2-notes-frontend/tree/main
https://github.com/fullstack-hy2020/part2-notes-frontend/tree/part5-3
https://github.com/fullstack-hy2020/part2-notes-frontend/tree/part5-9

**Comment by mluukkai** [comment]
fixed
