### ISSUE TITLE
Suggestion: showcase react apps that students built while learning your course

### ISSUE THREAD

**Issue by daattali** [fullstack-hy2020/fullstack-hy2020.github.io#314]
As I'm sure you're aware @mluukkai , this course was shared on reddit (and probably other websites as well) and is receiving a lot of usage outside of your university. 

I've been meaning to learn react for years, and this course has made me finally take that step. To put what I learn into use, I made a small project of my own, to test my knowledge halfway through part 2. I'm sure there are many others who also build small projects as a direct result of this course, so perhaps it would be motivational and inspirational to have a section on your course where you show what students are able to do after just 1-2 weeks of taking your course.

**Comment by fbkz** [comment]
Although I have no saying in the suggestion that was made, it is funny that I also _quit_ on part 2 to build a small side project. 

Back at it and I'm enjoying it a lot! Thank you for this course. 😁

**Comment by daattali** [comment]
Well, after looking at the names of the next parts, it seemed that they don't focus on React as much, so I figured I already have most of the React tools I'll learn in the course. But I'm sure Redux and TypeScript will help make your code more robust/cleaner once we learn that!

**Comment by BunnyTheLifeguard** [comment]
> Well, after looking at the names of the next parts, it seemed that they don't focus on React as much, so I figured I already have most of the React tools I'll learn in the course. But I'm sure Redux and TypeScript will help make your code more robust/cleaner once we learn that!

Don't you worry. React comes back in Chapter 5 and with important stuff 😉

**Comment by olav35** [comment]
Good idea. I am building a React/Node+WebSockets multiplayer type racing game called liracer as I am doing the course.

https://liracer.org/
https://github.com/olav35/liracer

There will probably be a little delay when you join because I am using Heroku free tier :p

**Comment by olav35** [comment]
> Well, after looking at the names of the next parts, it seemed that they don't focus on React as much, so I figured I already have most of the React tools I'll learn in the course. But I'm sure Redux and TypeScript will help make your code more robust/cleaner once we learn that!

I don't know if you have finished FSO by now, but there is a lot more React in part 5, 6 and 7. There are also small bits of React and frontend information spread throughout the other parts too.
