### ISSUE TITLE
Depecrate the part on `forwardRef`

### ISSUE THREAD

**Issue by avdb13** [fullstack-hy2020/fullstack-hy2020.github.io#3266]
In [part 5](https://fullstackopen.com/en/part5/props_children_and_proptypes#references-to-components-with-ref) the students get taught how to use the `forwardRef` hook. However, there is no clarification on when this should be used over lifting state.
Therefore I think this part should deprecated altogether since it just makes ones code unnecessarily more complicated.

**Comment by mluukkai** [comment]
Will not deprecate the part. I wrote a bit about that in the material why we now want the Togglable be a stand-alone component who is itself responsible for the state.
