### ISSUE TITLE
Part 7c: <Form.Group> usage inconsistent with documentation

### ISSUE THREAD

**Issue by cbohlman** [fullstack-hy2020/fullstack-hy2020.github.io#3280]
In the code example given for form usage there is only one `<Form.Group>` component wrapping both sets of `<Form.Labels>` and `<Form.Controls>`:

Current:
```
let Login = (props) => {
  // ...
  return (
    <div>
      <h2>login</h2>
      <Form onSubmit={onSubmit}>
        <Form.Group>
          <Form.Label>username:</Form.Label>
          <Form.Control
            type="text"
            name="username"
          />
          <Form.Label>password:</Form.Label>
          <Form.Control
            type="password"
          />
          <Button variant="primary" type="submit">
            login
          </Button>
        </Form.Group>
      </Form>
    </div>
  )
}
```

This code runs as expected, however according to the linked [documentation](https://react-bootstrap.netlify.app/docs/forms/form-control/), the `<Form.Group>` component should wrap each individual `<Form.Control>` component to link them together with other features such as `<Form.Label`, help text, etc. Proposing these changes to bring the code in the content in line with the documented guidelines.

Proposed Changes:
```
  return (
    <div>
      <h2>login</h2>
      <Form onSubmit={onSubmit}>
        <Form.Group>
          <Form.Label>username:</Form.Label>
          <Form.Control
            type="text"
            name="username"
          />
        </Form.Group>
        <Form.Group>
          <Form.Label>password:</Form.Label>
          <Form.Control
            type="password"
          />
        </Form.Group>
        <Button variant="primary" type="submit">
          login
        </Button>
      </Form>
    </div>
)}
```

**Comment by luchosr** [comment]
@cbohlman  Since this has already been resolved, could you please close this issue?

**Comment by cbohlman** [comment]
Apologies thought I had closed this, thanks for the nudge @luchosr
