### ISSUE TITLE
Unclear statement

### ISSUE THREAD

**Issue by smith558** [fullstack-hy2020/fullstack-hy2020.github.io#3290]
Page https://fullstackopen.com/en/part0/fundamentals_of_web_apps mentions in one of the paragraphs below a code snippet "The details of the code are not important right now, but some code has been included to spice up the **images** and the text.". But there are no images on the page. Perhaps a mistake and should only mention "text".

**Comment by mluukkai** [comment]
hmm, there are lots of images in the page:

<img width="1031" alt="image" src="https://github.com/user-attachments/assets/24ed1666-0ca5-407a-85e6-b4b7d26c2543">
