### ISSUE TITLE
[3.a] Replace CommonJS with ESM

### ISSUE THREAD

**Issue by demberto** [fullstack-hy2020/fullstack-hy2020.github.io#3369]
> Node supports now also the use of ES6 modules, but since the support is not quite perfect yet, we'll stick to CommonJS modules.

[Node docs on modules](https://nodejs.org/api/esm.html#modules-ecmascript-modules) say otherwise; way to go ESM.

**Comment by mluukkai** [comment]
After discussing with many developers, I concluded that the time is not yet right for ES modules. There are still too much problems  problems with some libraries
