### ISSUE TITLE
A passage in the Finnish version of 0b on the concept of fullstack is quite unclear

### ISSUE THREAD

**Issue by jparta** [fullstack-hy2020/fullstack-hy2020.github.io#3376]
The passage is

> Käytännössä kaikki web-sovellukset sisältävät (ainakin) kaksi "kerrosta" ylempänä eli lähempänä loppukäyttäjää olevan selaimen ja alla olevan palvelimen.

I have a hard time parsing what this means. Maybe I'm brainfarting, but I suspect this could be worded more clearly.

**Comment by mluukkai** [comment]
muutettu muotoon

_Käytännössä kaikki web-sovellukset sisältävät (ainakin) kaksi "kerrosta". Ylin kerros on lähempänä loppukäyttäjää oleva selain, joka suorittaa JaveScript-koodin ja renderöi sovelluksen HTML:n. Alempi kerros taas on sivuston tiedostot sisältämä palvelin. Palvelimen alapuolella on usein vielä tietokanta. Näin websovelluksen <i>arkkitehtuurin</i> voi ajatella muodostavan pinon, englanniksi <i>stack</i>._

**Comment by jparta** [comment]
Kiitos!
