### ISSUE TITLE
Translation omissions in Part 5d

### ISSUE THREAD

**Issue by Dilettante258** [fullstack-hy2020/fullstack-hy2020.github.io#3502]
In the section "_Testing note creation_" in **Part 5d**, there is a section in Finnish that has not been translated into English.

I didn't submit a PR because I thought it would be better for native speakers to do it.  @mluukkai 

![image](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/113875344/c399c9c1-abbe-4902-9767-7c5e414a8fbd)

**Comment by mluukkai** [comment]
fixed
