### ISSUE TITLE
Outdated ESLint Setup Instructions in Full Stack Open Part 3

### ISSUE THREAD

**Issue by mstflotfy** [fullstack-hy2020/fullstack-hy2020.github.io#3567]
The current instructions for setting up [ESLint in Part 3 of the Full Stack Open course](https://fullstackopen.com/en/part3/validation_and_es_lint#lint) seem to be outdated. The `npx eslint --init` command now prompts users to select a style guide, which creates an eslint.config.mjs file instead of the expected .eslintrc.js file.

The current course instruction is to run `npx eslint --init` which would start a prompt and we start answering questions:

![image](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/9896540/8980f3d5-24a6-481f-996d-3325842fb97a)

But when I run the command `npx eslint --init` the questions are a bit different. I'm forced to select a style guide to follow:

![image](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/9896540/262396f6-aec7-4035-8647-2c91b7c68a64)

This creates an `eslint.config.mjs` file instead of a `.eslintrc.js` file

By default ESLint plugin expects `.eslintrc.js` file, and so I go no errors in my files inside of VSCode. To make the errors appear I had to go the plugin's page -> Extension Settings -> and I had to check this option:

![image](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/9896540/3fd40821-2561-48f4-9af8-e7c52277ac2d)

This makes the plugin look for `eslint.config.mjs` files instead of `.eslintrc.js` and then the errors appeared inside the VSCode files.

An alternative method that also worked is to follow the same steps that are currently in the course. But isntead of running the command `npx eslint --init` create a `.eslintrc.js` file manually and copy the intial code from the example in the course and continue following the same steps. In this cade the `ESLint` plugin's option mentioned above must be unchecked if using VScode.

I think this part is currenltly confusing for people new to linting and might need an update.

**Comment by joelbarton-io** [comment]
I encountered the same problem with that section and using a `.eslintrc.js` file (like in the cirriculum) versus an `eslint.config.mjs` file (works with eslint v9+) and using the `nxp eslint --init` command. 

I found that going through vscode's command palette and selecting: `Eslint: Create Eslint Configuration` worked well enough and asked a few additional questions in the terminal setup dialog.

**Comment by mathdebate09** [comment]
pretty much the whole lot of linting section has become irrelevant, they don't support .eslintignore either and a lot of other legacy stuff

**Comment by ljcoogan** [comment]
I'm having the same problem as everyone else here. The section and subsequent exercises are confusing.

If anyone is doing the course and wants to do Exercise 3.22, I believe I managed to recreate the desired ESLint config file in the new format. Paste this inside `eslint.config.mjs` and see if it works.

```js
import globals from "globals";
import js from "@eslint/js";
import stylisticJs from '@stylistic/eslint-plugin-js';

export default [
  {files: ["**/*.js"], languageOptions: {sourceType: "commonjs"}},
  {languageOptions: { globals: { ...globals.browser, ...globals.node }}},
  js.configs.recommended,
  {
    plugins: {
      '@stylistic/js': stylisticJs
    },
    rules: {
      '@stylistic/js/indent': ['error', 2],
      '@stylistic/js/linebreak-style': ['error', 'unix'],
      '@stylistic/js/quotes': ['error', 'single'],
      '@stylistic/js/semi': ['error', 'never'],
      'eqeqeq': 'error',
      'no-trailing-spaces': 'error',
      'object-curly-spacing': ['error', 'always'],
      'arrow-spacing': ['error', {'before': true, 'after': true}],
      'no-console': 0
    },
  },
  {
    ignores: ["dist/*"]
  }
];
```

**Comment by mluukkai** [comment]
fixed
