### ISSUE TITLE
Change managed SQL recommendation since ElephantSQL is shutting down

### ISSUE THREAD

**Issue by felixbade** [fullstack-hy2020/fullstack-hy2020.github.io#3596]
Section [13a](https://fullstackopen.com/osa13/relaatiotietokannan_kaytto_sequelize_kirjastolla) suggests to use ElephantSQL as a managed SQL solution. However, ElephantSQL is [shutting down](https://www.elephantsql.com) in January 2025.

<img width="786" alt="Screenshot 2024-04-24 at 12 32 40" src="https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/6554998/12006f40-ad80-42b2-baf5-36870adf63f3">

ElephantSQL itself recommends migrating to Aiven for PostgreSQL.

**Comment by mluukkai** [comment]
removed
