### ISSUE TITLE
Expired Web certificate for the countries REST API

### ISSUE THREAD

**Issue by Travcort** [fullstack-hy2020/fullstack-hy2020.github.io#3730]
If you navigate to the link provided in **part2 (e) on Exercise 2.18**, it says that the web certificate for the site is expired.
The Link => [https://studies.cs.helsinki.fi/restcountries/]( https://studies.cs.helsinki.fi/restcountries/)
Please fix it so that we can continue learning.
Thank you for the course by the way. 
It is awesome!✔

**Comment by Alex-E-Clove** [comment]
Will add that this also affects the [submission site](https://studies.cs.helsinki.fi/stats/courses/fullstackopen) which is under the same domain (and that I agree that the course is great 👏)

**Comment by mluukkai** [comment]
fixed

**Comment by Travcort** [comment]
Thank you
