### ISSUE TITLE
Part 6d in Finnish uses outdated syntax for react-query

### ISSUE THREAD

**Issue by hojahoja** [fullstack-hy2020/fullstack-hy2020.github.io#3734]
The Finnish version of chapter 6d uses old syntax from version 4 of react-query and will cause issues if you try to follow along the course material since NPM will install the newer version.

English version of the material seems to be using the correct syntax.

**Example:**
Finnish material:
```js
  const newNoteMutation = useMutation(createNote, {
    onSuccess: (newNote) => {
      const notes = queryClient.getQueryData('notes')
      queryClient.setQueryData('notes', notes.concat(newNote))
    }
  })
```
English:
```js
  const newNoteMutation = useMutation({
    mutationFn: createNote,
    onSuccess: (newNote) => {
      const notes = queryClient.getQueryData(['notes'])
      queryClient.setQueryData(['notes'], notes.concat(newNote))
    }
  })
```

The one in Finnish material will outright break the app when ```createNote``` is passed as a parameter for ```useMutation``` and not in the object with the ```mutationFn:``` key

``` ...QueryData(['notes'])```  ```'notes'```also needs to be in the array or the function will just return undefined

There were a few code examples in the material that used this syntax, but this example highlighted both of the issues I noticed. There could be more later after the first set of exercises, but I haven't gotten that far yet.

**Comment by mluukkai** [comment]
fixed
