### ISSUE TITLE
Unable to install gatsby-cli

### ISSUE THREAD

**Issue by zs-5** [fullstack-hy2020/fullstack-hy2020.github.io#3772]
Following the [contributing guidelines](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/f1ee93cddfffb47cd6b936f46fe465d1e2459e7d/CONTRIBUTING.md), in step 4 (when running `npm install -g gatsby-cli`), the installation fails due to lmdb, preventing us from running it.

![gatsby-install-bug](https://github.com/user-attachments/assets/f1669a1b-6e18-407b-911a-f73b392ad85d)

Log file: [2024-08-15T22_44_13_017Z-debug.log](https://github.com/user-attachments/files/16631212/2024-08-15T22_44_13_017Z-debug.log)

I've also double checked the issue on a fresh vm.

**Comment by mluukkai** [comment]
you shoud use node 10, at least with 10.18 it works

**Comment by zs-5** [comment]
Just FYI: I *was* using Node 10 (as seen from the 2nd line of the log, node version 10.24.1), but maybe you're right, it might only work on 10.18.

**Comment by mluukkai** [comment]
ah

**Comment by mluukkai** [comment]
gatsby-cli is actually not needed, at least the global installation. will remove that step from the guidelines
