### ISSUE TITLE
Part 5d: Testing new note form - test runs before login is completed

### ISSUE THREAD

**Issue by peetaliu** [fullstack-hy2020/fullstack-hy2020.github.io#442]
Encountered an error where the test fails if your app already contains 'new note' somewhere on the page.

fullstack-hy2020.github.io/src/content/5/en/part5d.md
Section: Testing new note form (line 365)
```js
describe('Note app', function() {
  // ..
  describe('when logged in', function() {
    beforeEach(function() {
      cy.contains('login').click()
      cy.get('input:first').type('mluukkai')
      cy.get('input:last').type('salainen')
      cy.get('#login-button').click()
    })

    it('a new note can be created', function() {
      cy.contains('new note').click()
      cy.get('input').type('a note created by cypress')
      cy.contains('save').click()

      cy.contains('a note created by cypress')
    })
  })
})
```

![image](https://user-images.githubusercontent.com/46309091/82842738-aa796c00-9ea8-11ea-9e7b-ad6192526e71.png)

As you can see in the screenshot, the login succeeds, but the test is run before the login response is rendered. 
What's confusing is the test passes if your db doesn't contain anything with 'new note' even if we don't confirm login success. This is due to the [default assertions](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Default-Assertions) of cypress commands. 

> `cy.contains()` expects the element with content to eventually exist in the DOM.

If 'new note' text doesn't exist on the page, `cy.contains()` automatically retries when it does (in this case, after login success). However, since 'new note' existed in one of my note objects, `cy.contains()` referenced the rendered note object text right away instead of the new note button that would appear after our login success.

**_I think a small section on Assertions should be added to the course material to expand on the core functionality of Cypress commands._**

To temporarily get around this, I added `cy.contains('<your user name> logged in')` to the beforeEach() function after the login button is clicked. This confirms your login state before moving on to the tests.

```js
describe('Note app', function() {
  // ..
  describe('when logged in', function() {
    beforeEach(function() {
      cy.contains('login').click()
      cy.get('input:first').type('<your user name>')
      cy.get('input:last').type('<your password>')
      cy.get('#login-button').click()
      cy.contains('<your user name> logged in')
    })

    it('a new note can be created', function() {
      //...
    })
  })
})
```

This issue is avoided in the following section, **Bypassing the UI** (line 745), by using `cy.request()` to login rather than relying on the form.

**Comment by Kaltsoon** [comment]
This issue depends on the implementation. If the implementation relies on `display: none;` the `{ force: true }` option should fix this. If the implementation doesn't render the content at all (with e.g `{visible ? content : null}`) there shouldn't be any issues.
