### ISSUE TITLE
In part 3a, bodyParser is required to get the body of a request

### ISSUE THREAD

**Issue by charliebarber** [fullstack-hy2020/fullstack-hy2020.github.io#482]
In your example bodyParser is not used. From reading the documentation it says: 

> > req.body
> Contains key-value pairs of data submitted in the request body. By default, it is undefined, and is populated when you use body-parsing middleware such as body-parser and multer.

**Comment by Kaltsoon** [comment]
What about this: https://fullstackopen.com/en/part3/node_js_and_express#receiving-data ?

**Comment by charliebarber** [comment]
Does it not need require('body-parser') instead?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
