### ISSUE TITLE
part 8a - links to resolvers/default resolvers aren't correct

### ISSUE THREAD

**Issue by leo-vannini** [fullstack-hy2020/fullstack-hy2020.github.io#576]
resolvers/defaults resolvers links to the root page of the graphql-tools page (rather than what seems like previously the apollographql webpage):

https://www.graphql-tools.com/docs/introduction/#Resolver-function-signature

i think ultimately you want the following:
- "four parameters" link --> https://www.graphql-tools.com/docs/resolvers#resolver-function-signature
- "default resolvers" link --> https://www.graphql-tools.com/docs/resolvers#default-resolver

**Comment by Kaltsoon** [comment]
Thanks for pointing this out! The issue should be fixed now
