### ISSUE TITLE
Part 4c: jwt.verify error handling

### ISSUE THREAD

**Issue by kodonoboken** [fullstack-hy2020/fullstack-hy2020.github.io#578]
When testing token verification where the token is missing one letter, I receive the following error instead of the one mentioned in the lesson (JsonWebTokenError: invalid signature).  Extending my error handling middleware like as instructed  in the lesson did not fix this issue. I tried googling and couldn't find a solution I understood. I need help debugging this

```
Unexpected token < in JSON at position 25
Unexpected token < in JSON at position 25
SyntaxError: Unexpected token < in JSON at position 25
    at JSON.parse (<anonymous>)
```

Here is my list of dependency:
```
"dependencies": {
    "bcrypt": "^5.0.0",
    "cors": "^2.8.5",
    "cross-env": "^7.0.2",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-async-errors": "^3.1.1",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.15",
    "mongoose": "^5.9.20",
    "mongoose-unique-validator": "^2.0.3",
    "morgan": "^1.10.0"
  },
```

**Comment by Kaltsoon** [comment]
Could you ask about this in the course's telegram channel?
