### ISSUE TITLE
Part 4d: express-jwt link contains outdated information

### ISSUE THREAD

**Issue by jtarvainen** [fullstack-hy2020/fullstack-hy2020.github.io#611]
The course pages link to the following site for express-jwt:

https://www.npmjs.com/package/express-jwt

The information behind the link is outdated. For example, it doesn't mention that the 'algorithms' parameter is now mandatory. It might be better to link to this page instead:

https://github.com/auth0/express-jwt

**Comment by Kaltsoon** [comment]
Could you open a pull request that fixes this?

**Comment by jtarvainen** [comment]
Done!

**Comment by Kaltsoon** [comment]
Awesome, thanks!
