### ISSUE TITLE
Osa 1d, kieltoa voisi perustella paremmin

### ISSUE THREAD

**Issue by ppessi** [fullstack-hy2020/fullstack-hy2020.github.io#640]
Osiossa "Älä määrittele komponenttia komponentin sisällä" sanotaan "Mutta älä tee koskaan näin, eli määrittele komponenttia toisen komponentin sisällä. Tapa on hyödytön ja johtaa useissa tilanteissa ikäviin ongelmiin." Minusta olisi hyödyllisempää, jos perusteltaisiin, miksi näin ei kannata tehdä ja mitä ongelmia se tarkalleen ottaen aiheuttaa. On helpompi muistaa, miksei jotain saa tehdä, jos tietää miksi niin ei saa tehdä.

Osassa voisi myös mainita `onClick={() => doSomething()}` aiheutuvat mahdolliset performanssiongelmat edes sivulauseessa. Taisi olla maininta siitä, että on parempi tehdä `onClick={doSomething}`, mutta tätäkään ei perusteltu mitenkään.

**Comment by Kaltsoon** [comment]
Hyvä pointti, en ikävä kyllä löytänyt "virallista" kieltoa, mutta selitin ongelman parhaan kykyni mukaan. 

`onClick={() => doSomething()}` vs. `onClick={doSomething}` on 99% tapauksista tarpeetonta optimointia, enkä ehkä hämmentäisi opiskelijoita sillä (pitäisi esim. avata [useCallback](https://reactjs.org/docs/hooks-reference.html#usecallback)-hookia ja memoisaatiota)
