### ISSUE TITLE
0b - Broken link for Finish app

### ISSUE THREAD

**Issue by jmauriciowebdev** [fullstack-hy2020/fullstack-hy2020.github.io#687]
Hello, the link for the Finish app which I believe is hosted in Vercel is broken! The multilingual one on Heroku is running still.

**Comment by Kaltsoon** [comment]
Can you share the broken link?

**Comment by jmauriciowebdev** [comment]
Sure, it's the link of the web app.
https://fullstack-example.now.sh/

![image](https://user-images.githubusercontent.com/50447692/91177203-4484c680-e6db-11ea-90f4-df175978733e.png)

**Comment by Kaltsoon** [comment]
Where's this link in the material exactly? Couldn't find it while doing a search in the material

**Comment by jmauriciowebdev** [comment]
Right at the beginning!
![image](https://user-images.githubusercontent.com/50447692/91187972-af88ca00-e6e8-11ea-9593-9dcfb10f6ced.png)

The link was probably updated in the Finnish documentation but maybe you forgot about the English version?

**Comment by Kaltsoon** [comment]
Got it, thanks! We'll look into this

**Comment by jmauriciowebdev** [comment]
No problem, glad I could help your amazing project a tiny bit!
Thank you! 🙂

**Comment by Kaltsoon** [comment]
This issue should now be fixed. Thanks for the help!
