### ISSUE TITLE
Part 10 is starting translating to Chinese(Zh)。

### ISSUE THREAD

**Issue by RichardStark** [fullstack-hy2020/fullstack-hy2020.github.io#712]
Hi guys，I am doing the translation work from en version to zh version, and the part 10 is starting. 
Anyone be interested in doing the same task, feel free to contact me.
wechat: richardzhangv

**Comment by RichardStark** [comment]
I have finished this part, feel free to PR

**Comment by Kaltsoon** [comment]
Thanks, @RichardStark, this is a huge contribution!
