### ISSUE TITLE
part1a: Confusing sentence about index.html being empty

### ISSUE THREAD

**Issue by nfabredev** [fullstack-hy2020/fullstack-hy2020.github.io#720]
In [part1a](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/source/src/content/1/en/part1a.md) the following sentence can be found:

```
By default, the file public/index.html is empty.
```

However the file is not empty, it would only render a visually empty page if opened with a browser. The formulation of the sentence is a bit confusing and the paragraph it starts could be changed to:

```
The `public/index.html` file wouldn't render any content if opened in the browser. You could write HTML in there to add content to it, but when using React, all content that needs to be rendered is usually defined as React components.
```

Maybe leaving as an exercise to the student to compare the content seen in the developer tools of the browser of the html file and what's served with the development server. That could either be confusing, or be seen as a starting point to read about the dev server / build step of a react app if that's in scope for the course.

Let me know if you want a PR about any of these two things, happy to contribute.

**Comment by Kaltsoon** [comment]
Yes, it's a bit misleading. I rephrased that sentence, but feel free to improve my version with a pull request.
