### ISSUE TITLE
Part 7c: wrong library reference on Finnish page

### ISSUE THREAD

**Issue by jtarvainen** [fullstack-hy2020/fullstack-hy2020.github.io#726]
The Finnish page for Part 7c contains the following text:

> renderöidään komponentti Button, siten että sen juurikomponenttina onkin react-redux-kirjaston komponentti Link, jolle siirtyy polun kertova props to.

The referenced library should instead be 'react-router-dom', and the text should be (emphasis mine):

> renderöidään komponentti Button, siten että sen juurikomponenttina onkin **react-router-dom**-kirjaston komponentti Link, jolle siirtyy polun kertova props to.

The text is correct on the English page.

**Comment by Kaltsoon** [comment]
Could you create a pull request that fixes this issue?

**Comment by jtarvainen** [comment]
Done!

Jussi

**Comment by Kaltsoon** [comment]
Thanks!
