### ISSUE TITLE
Course content does not mention React Native

### ISSUE THREAD

**Issue by MuathAmer** [fullstack-hy2020/fullstack-hy2020.github.io#727]
The course content in English does not mention React Native as far as I see, it says there are 10 sections, but now they are 11. 
Also, the home page does not mention that React Native has been added.

I would love to do this if no one has done it already.

**Comment by johan456789** [comment]
Part 10 is React Native. Where did you see part 11?

![image](https://user-images.githubusercontent.com/14802181/92104222-9f24cd80-ee13-11ea-9126-1c2698d0049e.png)

**Comment by MuathAmer** [comment]
In the "general info", it doesn't mention React Native, neither it does in the "Announcements" section or the home page.

In the "taking the course" part, it says that there is 10 parts, where the first is 0.
That's wrong, there are 11 parts, first is 0, last is 10.

I know that's a nitpick 😅

![Screenshot_20200903-190810__01](https://user-images.githubusercontent.com/7873900/92284087-fc02af80-ef09-11ea-8501-9aac7e34c6de.jpg)
![Screenshot_20200903-190717__01](https://user-images.githubusercontent.com/7873900/92284088-fdcc7300-ef09-11ea-9e4d-8b94cf85ecba.jpg)

**Comment by Kaltsoon** [comment]
These are good points! I just altered part 0, feel free to reopen this issue, if it contains further issues.
