### ISSUE TITLE
Part 10a: Expo mobile client app requires local network access to run

### ISSUE THREAD

**Issue by tveijola** [fullstack-hy2020/fullstack-hy2020.github.io#735]
In order to download the javascript bundle to personal mobile device using Expo client, the device must be connected to the same local network as the computer running Expo DevTools.

Another option is to set Connection from LAN to Tunnel.

Consider adding a note about this.

**Comment by Kaltsoon** [comment]
That's true, we have added notes to https://fullstackopen.com/en/part10/communicating_with_server:

> Note that if you are using an emulator for development it is recommended to run the server and the emulator on the same computer. This eases network requests considerably.

And

> If you are using the Expo's mobile app for development and the network request is failing, make sure that the computer you are using to run the server and your phone are connected to the same Wi-Fi network. If that's not possible either use an emulator in the same computer as the server is running in or set up a tunnel to the localhost, for example, using Ngrok.

Did you face network issues in some parts of the material before part10c?

**Comment by tveijola** [comment]
There was a mention in Part10a: Setting up the development environment.

> When the Expo mobile app is finished installing, open it up. Next, if the Expo development tools is not already running, start it by running npm start. In the bottom left corner of the development tools, you should be able to see a QR code. Within the Expo mobile app, press Scan QR Code and scan the QR code displayed in the development tools. The Expo mobile app should start building the JavaScript bundle and after it is finished you should be able to see your application. Now, every time you want to reopen your application in the Expo mobile app, you should be able to access the application without scanning the QR code by pressing it in the Recently opened list in the Projects view.

**Comment by Kaltsoon** [comment]
I added a note to part10a as well, if someone has difficulties opening the application in the Expo mobile app. Thanks for pointing this out!
