### ISSUE TITLE
Part 1c

### ISSUE THREAD

**Issue by orvalho** [fullstack-hy2020/fullstack-hy2020.github.io#765]
In Part 1c there is this sentence:
![image](https://user-images.githubusercontent.com/17577228/92789139-39a48400-f3b3-11ea-8fde-625c5c2ff67f.png)

The problem is that **it's unclear what exactly the _render_ function is**. 

In the material, the _render_ method was only mentioned in the context of ReactDOM (ReactDOM.render). However, I'm guessing it's not it.

After doing some research, I figure that everything inside the body of a function, that defines a component, is the _render_ function. Am I right?

My suggestion is to add an explanation of what the _render_ function is or don't mention the _render_ function at all to avoid any confusion. What do you think?

**Comment by Kaltsoon** [comment]
> After doing some research, I figure that everything inside the body of a function, that defines a component, is the render function. Am I right?

Yes, that's right. Highlighting the render function as code is a bit misleading and might lead to people trying to find a function called `render`. Maybe this would make more sense:

"It's easy to follow and track the calls made to the `App` component's render function:"

Any comments or ideas?

**Comment by orvalho** [comment]
Yes, removing highlighting from the render function definitely helps to avoid confusion. 
I think that the meaning of the sentence is clearer now.
