### ISSUE TITLE
Security concerns. Worried you're teaching awful security practices

### ISSUE THREAD

**Issue by robhutters** [fullstack-hy2020/fullstack-hy2020.github.io#766]
For reference, I'm working through exercises 5.1-5.4 as we speak. (Maybe my concerns will be addressed later in the course)

I'm basing my concerns on this blog post [Stop Using JWT for Sessions](http://cryto.net/%7Ejoepie91/blog/2016/06/13/stop-using-jwt-for-sessions/)

Issues:

- JWTs are supposed to be short lived tokens, yet we're using them to store session data that never expires.
- Relying on users to logout for the token to clear. You're one XSS attack away from having a bad time.

> Stateless JWT tokens cannot be invalidated or updated, and will introduce either size issues or security issues depending on where you store them. Stateful JWT tokens are functionally the same as session cookies, but without the battle-tested and well-reviewed implementations or client support. (from the article)

Why did you choose to teach using JWT for sessions instead of cookies?

**Comment by Kaltsoon** [comment]
I totally agree that using local storage to store the access token and relying on JWT's expiration to invalidate the access token isn't ideal. I'm not aware of the reasons why this decision was made, I think it was just convenient and a "good enough" way to handle authentication.

We have discussed changing the authentication material a few times. In my opinion, it would be a good idea to instruct people to store access tokens as HTTP only cookies and to store them in the database so that real token invalidation (for example after logout) is possible. How does this sound to you?

**Comment by sahilrajput03** [comment]
> I totally agree that using local storage to store the access token and relying on JWT's expiration to invalidate the access token isn't ideal. I'm not aware of the reasons why this decision was made, I think it was just convenient and a "good enough" way to handle authentication.
> 
> We have discussed changing the authentication material a few times. In my opinion, it would be a good idea to instruct people to store access tokens as HTTP only cookies and to store them in the database so that real token invalidation (for example after logout) is possible. How does this sound to you?

Would you recommend any sources on how to implement what you are saying, I understand what you said, but it would be great to have a simple demo/tutorial/source on this practise. 
Thanks.

**Comment by Kaltsoon** [comment]
> > I totally agree that using local storage to store the access token and relying on JWT's expiration to invalidate the access token isn't ideal. I'm not aware of the reasons why this decision was made, I think it was just convenient and a "good enough" way to handle authentication.
> > We have discussed changing the authentication material a few times. In my opinion, it would be a good idea to instruct people to store access tokens as HTTP only cookies and to store them in the database so that real token invalidation (for example after logout) is possible. How does this sound to you?
> 
> Would you recommend any sources on how to implement what you are saying, I understand what you said, but it would be great to have a simple demo/tutorial/source on this practise.
> Thanks.

The authorization method I described is somewhat a simplified version of the [OAuth](https://oauth.net/2/) authorization protocol.

**Comment by sahilrajput03** [comment]
Woww!! 😍You know @Kaltsoon that we can enbale fingerprint security with oauth2, I tested it with my phone mid of last year, and it really amazed with that such functionality can be achieved with BROWSER ONLY.

## You can see a few resources I collected for this to work(test) in mid of last year. If you get some time, check here there at - https://sahilrajput03.github.io/fido2,webauth.html . 
As I wrote there - 

### https://webauthndemo.appspot.com/ • working like river.

### https://webauthn.me/ • working like river.(must analyse now - as the animation shows the behind the screen process beautifully)

### http://webauthn.io/ • working like river.

Its really fun to test this authentication there, and good things is we can test fingerprint authorizaion right inside browser with this chrome browser, i.e. https://chrome.google.com/webstore/detail/virtual-authenticators-ta/gafbpmlmeiikmhkhiapjlfjgdioafmja


Thanks, @Kaltsoon .
And what do you think👀👀 about this fido2 (fingerprint authentication, which is already implemented with atleast chrome on android).

**Comment by janLuke** [comment]
This looks like a huge issue to me, both technically a didactically. It's very frustrating and disheartening, as I student, to realize you're learning and applying bad practices. Any plan to fix this in the short term? @Kaltsoon

**Comment by mluukkai** [comment]
This will be addressed in 2021 edition
