### ISSUE TITLE
Adam Ondra and Janja Garnbret

### ISSUE THREAD

**Issue by jeffchiou** [fullstack-hy2020/fullstack-hy2020.github.io#781]
[https://fullstackopen.com/en/part1/java_script#classes](https://fullstackopen.com/en/part1/java_script#classes)

```
const adam = new Person('Adam Ondra', 35)
adam.greet()

const janja = new Person('Janja Garnbret', 22)
janja.greet()
```

They seem a bit too old in the code. Alex Honnold is 35 though...

**Comment by Kaltsoon** [comment]
I don't think the actual age is relevant in the scope of this example
