### ISSUE TITLE
HOC are a little bit less explained in course, react docs has a example in this exact context.

### ISSUE THREAD

**Issue by sahilrajput03** [fullstack-hy2020/fullstack-hy2020.github.io#783]
![image](https://user-images.githubusercontent.com/31458531/93028523-0d4a6b00-f632-11ea-81ab-1328e3d40e5f.png)

This example is very important to explaing the higher order component's design of coonect function of redux.

Above e.g., is from src: https://reactwithhooks.netlify.app/docs/higher-order-components.html#convention-maximizing-composability

**Comment by Kaltsoon** [comment]
I thin the end of this chapter wraps up HOCs quite well: https://fullstackopen.com/en/part6/connect#presentational-container-revisited. Also, at the moment the trend is to use hooks over HOCs and this trend will most likely continue in the future.

**Comment by sahilrajput03** [comment]
I like hooks over HOC's too. 
Thanks. The material is updated,I couldn't see the updates at once, the article references are really good. REALLY LIKED THEM.
Thanks. :)
