### ISSUE TITLE
Part 8c: wrong mongodb password in uri

### ISSUE THREAD

**Issue by jtarvainen** [fullstack-hy2020/fullstack-hy2020.github.io#794]
The example code snippet on the course page for Part 8 gives the MONGODB_URI value as follows:

> const MONGODB_URI = 'mongodb+srv://fullstack:sekred@cluster0-ostce.mongodb.net/graphql?retryWrites=true'

This uri cannot be used to login to the example database; it gives the error "bad auth Authentication failed".

[The full example code for the part in question](https://github.com/fullstack-hy2020/graphql-phonebook-backend/blob/part8-4/index.js) contains the correct uri (note the password 'halfstack' instead of 'sekred'):

> const MONGODB_URI = 'mongodb+srv://fullstack:halfstack@cluster0-ostce.mongodb.net/gql-phonebook?retryWrites=true'

Should the course page also use this same uri?

**Comment by Kaltsoon** [comment]
I think it's a mistake. Could you open a pull request that fixes this?

**Comment by jtarvainen** [comment]
Done! (I made the edit to the Finnish, English, and Chinese pages.)

**Comment by Kaltsoon** [comment]
Awesome, thanks!
