### ISSUE TITLE
Exercise 5.5 provides wrong button text in the screenshot

### ISSUE THREAD

**Issue by iownthegame** [fullstack-hy2020/fullstack-hy2020.github.io#815]
`new note` button should change to `create new blog` in the [image](https://fullstackopen.com/static/de4cfabdf46a837f1f0bfdba4fd27d67/5a190/13ae.png)

<img src="https://fullstackopen.com/static/de4cfabdf46a837f1f0bfdba4fd27d67/5a190/13ae.png" />

**Comment by robsondepaula** [comment]
The PR https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/pull/1329 should take care of this issue.
