### ISSUE TITLE
Typescript for everything ?

### ISSUE THREAD

**Issue by sycured** [fullstack-hy2020/fullstack-hy2020.github.io#819]
Hello,
Is it possible to replace javascript by typescript for every part?

For example, inside the part1, we need to do: `npx create-react-app part1`
We can add one parameter to move it to typescript: `npx create-react-app part1 --template typescript`

Thanks

**Comment by Kaltsoon** [comment]
Sure you can. We don't mention this in the material, because we don't want to encourage people not familiar with TypeScript to do this.
