### ISSUE TITLE
Part 9b: @types/node requires tsconfig.json to work?

### ISSUE THREAD

**Issue by jtarvainen** [fullstack-hy2020/fullstack-hy2020.github.io#824]
According to Part 9b, installing the npm package @types/node provides access to Node's global variables, such as _process_. For me, installing the package (locally, for this project only) wasn't enough: **I also had to create a tsconfig.json file**. What's more, the file could even be empty!

I'm currently using the following:
- Visual Studio Code 1.49.2 (MacOS)
- @types/node 14.11.2
- ts-node 9.0.0
- typescript 4.0.3

Can you reproduce the issue and/or suggest further action?

**Comment by Kaltsoon** [comment]
Couldn't reproduce this. Does the `ts-node` command fail, or what's the issue? What's the error output?

**Comment by jtarvainen** [comment]
I've since reinstalled VS Code and now can't reproduce the issue either, so I guess this issue can be closed. :-) Sorry for the false alarm!

**Comment by Kaltsoon** [comment]
Excellent!
