### ISSUE TITLE
Part5c 'CI' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by p4nu** [fullstack-hy2020/fullstack-hy2020.github.io#848]
when following the tutorials with windows 10 I get this error when trying to run CI=true npm test

`'CI' is not recognized as an internal or external command,
operable program or batch file.`

what needs to be done to fix this?

**Comment by Kaltsoon** [comment]
Using [cross-env](https://www.npmjs.com/package/cross-env) should fix this.
