### ISSUE TITLE
Part 8c: Handling Mutation Error

### ISSUE THREAD

**Issue by kodonoboken** [fullstack-hy2020/fullstack-hy2020.github.io#885]
I ran the example graphql-phonebook-backend and graphql-phonebook-frontend and came across the same error as in my library app. Looks like the response we are expecting from Apollo Client is different than the type that is returned. 

```javascript
Unhandled Rejection (TypeError): Cannot read property 'message' of undefined
onError
src/components/PersonForm.js:16
  13 | const [ createPersom ] = useMutation(CREATE_PERSON, {
  14 |   refetchQueries: [  {query: ALL_PERSONS} ],
  15 |   onError: (error) => {
> 16 |     setError(error.graphQLErrors[0].message)
     | ^  17 |   }
  18 | })
  19 | 
```

**Comment by Kaltsoon** [comment]
The obvious issue is that `graphQLErrors` is empty, but it hard to tell why.  Could you inspect the error in a bit more detail, by e.g. checking what the `error.message` is?

**Comment by kodonoboken** [comment]
I went back and change backend to run part8-2 branch with the UserInputError code and it runs now. I may not have implemented error handling on my backend. Does the onError only work when I use UserInputError on backend? It's not automatically handled by GraphQL validation?

**Comment by Kaltsoon** [comment]
It should catch all error types. Feel free to reopen this issue, if you face further trouble.
