### ISSUE TITLE
Part 7d - webpack-dev-server not working with webpack v5

### ISSUE THREAD

**Issue by jpparkkari** [fullstack-hy2020/fullstack-hy2020.github.io#896]
There's some complications with webpack-dev-server and webpack v5 (which is btw not updated anymore, since 2018).
I got the dev server running by using webpack serve. 
"start": "webpack serve --mode development"

I could do a pull request but that would require more or less rewriting the whole webpack-dev-server chapter, and I'm not sure if webpack-dev-server can just be replaced with webpack serve, and if webpack.config.js is still valid. I also don't know how this works with webpack v4.

Here's the error I got from npm start (macOS Catalina)
`> webpack-dev-server --mode=development

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- <pathToFolder>/part7-webpack/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (<pathToFolder>/part7-webpack/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '<pathToFolder>/part7-webpack/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-osa7@0.0.1 start: `webpack-dev-server --mode=development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack-osa7@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by Kaltsoon** [comment]
Could you try this: https://github.com/webpack/webpack-dev-server/issues/2239#issuecomment-530816822 ? If this issue is fixed soon, perhaps there's no need to change the material

**Comment by jpparkkari** [comment]
It seems the problem actually is webpack-cli v4. v3.3.8 works.

**Comment by Kaltsoon** [comment]
Ended up with the `webpack serve --mode development` as the `start` script as you suggested.  Thanks for the help!

**Comment by Alicelijia** [comment]
> v3.3.8
{
    "webpack": "^5.4.0",
    "webpack-cli": ^4.2.0",
    "webpack-dev-server": "^3.7.1"
}
Error: Cannot find module 'webpack-cli/bin/config-yargs'
If i change to v3.3.8 it works well

**Comment by Alicelijia** [comment]
> It seems the problem actually is webpack-cli v4. v3.3.8 works.
{
    "webpack": "^5.4.0",
    "webpack-cli": "^4.0.0 ",
    "webpack-dev-server": "^3.11.0"
}
Error: Cannot find module 'webpack-cli/bin/config-yargs'
if i change webpack-cli version to ^3.3.8 it  works
