### ISSUE TITLE
Let's add Dark Mode!

### ISSUE THREAD

**Issue by jayeshmann** [fullstack-hy2020/fullstack-hy2020.github.io#918]
It blinds **eyes** along with **mind**, while changing from vscode _dark-theme_ to _light-themed_ website.

**Comment by sahilrajput03** [comment]
Actually there is an un official theme for fso site.

You can enable it via installing this chrome extension - https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe

The page for theme is => https://userstyles.org/styles/172207/full-stack-open-2019-darkcss-and-header-fix

Thanks.

**Comment by johan456789** [comment]
@sahilrajput03  Thanks for sharing. It's actually quite good in the course content part, but in the exercise part the color is not changed and a bit too bright.

**Comment by sahilrajput03** [comment]
@johan456789 , I am a big fan of dark mode while browsing, and I always prefer https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh this extension.

Also, this extension has very cool features like, alt+shift+e will toggle dark mode for a particular site, and this extension will enable dark mode for that site only.

But this extension does this dark mode thing amazing, and I use if for almost every website, like github/google/fso.

**Comment by sahilrajput03** [comment]
If you don't like shortcuts, you can simply browse any website that you wanna enable darkmode, and click that site name there. 

![image](https://user-images.githubusercontent.com/31458531/96858526-fd6a4600-147d-11eb-8d08-d3180f962acb.png)
