### ISSUE TITLE
Moment.js in 'Useful libraries and interesting links'

### ISSUE THREAD

**Issue by virenb** [fullstack-hy2020/fullstack-hy2020.github.io#946]
URL: [https://fullstackopen.com/en/part7/class_components_miscellaneous#useful-libraries-and-interesting-links](https://fullstackopen.com/en/part7/class_components_miscellaneous#useful-libraries-and-interesting-links)

Last month, the Moment.js provided a project update ([https://momentjs.com/docs/#/-project-status/](https://momentjs.com/docs/#/-project-status/)), mentioning _'We now generally consider Moment to be a legacy project in maintenance mode. It is not dead, but it is indeed done.'_

It has been a very useful tool but maybe should be taken off the page? Or maybe keep it on but have a note mentioning how it was a very popular tool but not recommended as of October 2020?

Would be glad to open a PR to update this page if you'd like it removed or the note to be added.

**Comment by Kaltsoon** [comment]
True, Moment isn't relevant anymore. Could you open a PR that removes the Moment mention and only contains `date-fns`?

**Comment by virenb** [comment]
Sounds good, I have opened a PR. I noticed there was a comment, which was a Finnish translation. I did not want to edit it as I don't know Finnish and Google Translate is not always the most accurate.

**Comment by Kaltsoon** [comment]
Thanks! I'll handle the Finnish translation
