### ISSUE TITLE
Suggestion for in-depth understanding of "this" leads to paid course

### ISSUE THREAD

**Issue by fcole90** [fullstack-hy2020/fullstack-hy2020.github.io#967]
In paragraph https://fullstackopen.com/en/part1/java_script#object-methods-and-this, at the end, it is suggested to follow a clarification course on egghead.io. However, only part 1 is directly accessible, as part 2 requires signup and parts >= 3 all need membership, which is about $250/year (https://egghead.io/pricing?from=pro%20lesson).

Can you replace it with a freely available resource?

**Comment by Kaltsoon** [comment]
Sure! If you know any good free sources, we will gladly accept a pull request.

**Comment by fcole90** [comment]
If I find some, I'm definitely going to suggest them :blush:
