### ISSUE TITLE
10d: updates to component's input variable from within component?

### ISSUE THREAD

**Issue by jtarvainen** [fullstack-hy2020/fullstack-hy2020.github.io#969]
In the beginning of Part 10d, the RepositoryList component is refactored into RepositoryList and RepositoryListContainer, where the former calls the latter with the _repositories_ variable obtained with the useRepositories hook. RepositoryListContainer then renders the repositories with FlatList.

Later, in exercises 10.23 and 10.24, the FlatList is extended to contain sorting and filtering functionalities, respectively. The student is advised to create these with the ListHeaderComponent prop. However, since the sort and filter both affect the repositories variable, which is created outside the RepositoryListContainer component, how are we to handle updates to the repositories while still keeping the RepositoryListContainer component "pure" as instructed? Are we supposed to use Redux to create a global store for the repositories variable, or is there another way?

EDIT 14.11.2020: Also, related to the above, I'm witnessing some odd behavior related to the RepositoryListContainer class component and the "key" property. If I don't give the RepositoryListContainer a "key" property, the sorting functionality doesn't work properly (sometimes it freezes and sometimes it only performs the first one or two sorts). Also, without the "key" property, additional repositories fetched with the fetchMore function are not automatically updated to the list. If, however, I add a random key as one of the RepositoryListContainer properties ( key={Math.random()} ), then sorting and infinite scrolling both work, but whenever the list is updated, the whole page is refreshed and the view jumps to the top of the page. How could I fix this? (As a side note, a single repository's review list, which does not use a class component, works fine).

**Comment by Kaltsoon** [comment]
These are the props for the `RepositoryListContainer` in the model solutions:

```javascript
<RepositoryListContainer
    repositories={repositories}
    orderBy={orderBy}
    onOrderByChange={...}
    onEndReach={onEndReach}
    searchKeyword={searchKeyword}
    onSearchKeywordChange={...}
    onRepositoryPress={...}
/>
```

Basically `RepositoryList` contains the state (e.g. current filter) and passes props like `onSearchKeywordChange` for altering the state. The `RepositoryListContainer` has no state and is free from side effects. You can use Redux if you want but the model solution only uses the good old `useState` hook.

**Comment by jtarvainen** [comment]
Ok, thanks, that makes sense. It turns out my issue was caused by the fact that I had defined the class component's _repositoryNodes_ variable in the class body instead of in its render() function. Once I moved the definition within the render() function, I could (and, in fact, had to) also remove the random key from the RepositoryList properties.
