### ISSUE TITLE
AsyncStorage is deprecated, remove it, as its throwing exception browser!!!

### ISSUE THREAD

**Issue by sahilrajput03** [fullstack-hy2020/fullstack-hy2020.github.io#971]
![image](https://user-images.githubusercontent.com/31458531/99148910-a0466680-26b0-11eb-9cd5-976c41c0cbeb.png)

## I get this exception in browser, but it works in device. 

Fix this as suggested in the hower,#in image.

Thanks, Sahil.

**Comment by Kaltsoon** [comment]
Material is already using `@react-native-community/async-storage`: https://fullstackopen.com/en/part10/communicating_with_server#storing-data-in-the-users-device

**Comment by sahilrajput03** [comment]
Ohh.., I didn't notice that..., :ok_hand:

**Comment by sahilrajput03** [comment]
> ![image](https://user-images.githubusercontent.com/31458531/99148910-a0466680-26b0-11eb-9cd5-976c41c0cbeb.png)

hey, kalle its still throwing error in web like this.., is asyncStorage only works in android/ios and not web?

**Comment by sahilrajput03** [comment]
@Kaltsoon ^^^^^^666
