### ISSUE TITLE
Postman installation instructions missing

### ISSUE THREAD

**Issue by mattmartini** [fullstack-hy2020/fullstack-hy2020.github.io#985]
In part 3 it states "Let's install Postman and try it out," but then there are no instructions for installing or using Postman.  I don't think you have to spoon feed everything in the course, but some hints on installation and configuration would be nice, especially as Postman is a tool to help explore the topic of the course and not the topic itself.

**Comment by mattmartini** [comment]
So after trying Postman via their website, adding a local agent, using the (now depreciated) Chrome extension, I discovered that there is a native app.  The native app is easy to use.
Just adding a sentence to the effect that there is a native app would be very helpful!

**Comment by mluukkai** [comment]
fixed in 2022 edition
