### ISSUE TITLE
Second example in Part1.d - function that returns a function feels wrong

### ISSUE THREAD

**Issue by aviekakkar** [fullstack-hy2020/fullstack-hy2020.github.io#989]
https://fullstackopen.com/en/part1/a_more_complex_state_debugging_react_apps#function-that-returns-a-function

![Screen Shot 2020-12-02 at 2 27 13 PM](https://user-images.githubusercontent.com/18153854/100850893-7a8bd080-34aa-11eb-8a8a-5ab970447f04.png)

Shouldn't the second example return the setValue function - that is responsible for updating state, into a normal function?

instead of <button onClick={() => setToValue(1000)}> thousand </button>
shouldn't it be, <button onClick={()=> setValue(1000)}> thousand </button>

**Comment by Kaltsoon** [comment]
Both work, `setValue(1000)` and `setToValue(1000)` do the same thing, if `setToValue` is the following:

```js
const setToValue = (newValue) => {
    setValue(newValue)
}
```

**Comment by aviekakkar** [comment]
Surely, however isn't using setToValue returning another function? 

As it states "Using functions that return functions is not required to achieve this functionality. " And the purpose of this example is to show that it can be done directly using setValue?

**Comment by Kaltsoon** [comment]
> Surely, however isn't using setToValue returning another function?

There are two implementations, but the example you are referring to (correct me if I'm wrong) seems to be the implementation I'm referring to in my comment:

```js
const App = () => {
  const [value, setValue] = useState(10)

  const setToValue = (newValue) => {
    setValue(newValue)
  }

  return (
    <div>
      {value}
      <button onClick={() => setToValue(1000)}>
        thousand
      </button>
      <button onClick={() => setToValue(0)}>
        reset
      </button>
      <button onClick={() => setToValue(value + 1)}>
        increment
      </button>
    </div>
  )
}
```

I didn't write this part, but I think the point is to show different ways of using event handlers. There's the "builder pattern", which uses a function that returns a function (`setToValue = () => (newValue) => ...`) and the "inline pattern" which uses an inline arrow function as the event handler.

**Comment by aviekakkar** [comment]
so I dug into this part again today and here are my observations, 

Yes, you're correct in that there are two examples given, and we're discussing the second implementation, also correctly referred by you. 

For clarification:
**First** example: the **Builder Pattern**
**Second** example: the **Inline Pattern**

And yes they both work, as you have also mentioned. 

> Both work, `setValue(1000)` and `setToValue(1000)` do the same thing, if `setToValue` is the following:
> 
> ```js
> const setToValue = (newValue) => {
>     setValue(newValue)
> ```


So my main issue I had was not that the examples provided don't work, but with the description and reasoning for showing the second example (**Inline Pattern**). 

As I stated the particular line that is given as the reason for showing the second example 
**"Using functions that return functions is not required to achieve this functionality"** 
expects to be followed by an example that shows this can be done "without using functions that return functions" but is instead showing just an inline pattern of using functions that return functions
 
Hence, my first concern that either the example is incorrect(due to the description/reason provided) or the description is misleading.

I hope the issue is more clearer now
