### ISSUE TITLE
Part 5c (Testing React apps): jest coverage report does not work with render() of react-testing-library

### ISSUE THREAD

**Issue by iFork** [fullstack-hy2020/fullstack-hy2020.github.io#992]
When I run test with coverage flag I get error about `Nothing was returned from render.`
Everything is fine without coverage flag.

## Some related issues
- [render does not work with jest coverage report. · Issue #622 · testing-library/react-testing-library](https://github.com/testing-library/react-testing-library/issues/622)
- [Nothing was returned from render. · Issue #663 · testing-library/react-testing-library](https://github.com/testing-library/react-testing-library/issues/663#issuecomment-626810810)
- [Coverage report not working · Issue #7838 · facebook/create-react-app](https://github.com/facebook/create-react-app/issues/7838)

## Attempted Solutions
I attempted following approaches but I always get error 

### 1. Using [jest-environment-jsdom-sixteen - npm](https://www.npmjs.com/package/jest-environment-jsdom-sixteen)
> `CI=true npm test -- --coverage --env=jest-environment-jsdom-sixteen --coverageProvider=v8`

But `coverageProvider` is not listed under cra's supported coverage overrides.

### 3. Using ts-jest as jest transformer

> install `ts-jest`.
> ```
> "jest": {
>     "transform": {
>       "^.+\\\.(js|jsx|ts|tsx)$": "<rootDir>/node_modules/ts-jest"
>     }
> }
> ```

## Package versions
```
├── @testing-library/jest-dom@4.2.4
├── @testing-library/react@9.5.0
├── @testing-library/user-event@7.2.1
├── axios@0.19.2
├── jest-environment-jsdom-sixteen@1.0.3
├── json-server@0.16.2
├── prop-types@15.7.2
├── react@16.14.0
├── react-dom@16.14.0
└── react-scripts@3.4.0
```

**Comment by mluukkai** [comment]
seems to be ok now
